### ISSUE TITLE
Native Code Crush

### ISSUE THREAD

**Issue by Railer** [deeplearning4j/libnd4j#102]
While running Nd4j (code_1) in order to normalize some data for clustering I run in the following crush (pid_1). This has been confirmed on both Linux - Fedora Server 23 and Windows 10 
. The data are loaded from a database and then converted to a primitive array. When testing with Nd4j random, everything runs fine (code_2). This happenend occured only after changing from nd4jx86 to nd4j-native. The data dimensions are 35000 x 4.
[code_2.txt](https://github.com/deeplearning4j/libnd4j/files/212849/code_2.txt)
[code_1.txt](https://github.com/deeplearning4j/libnd4j/files/212851/code_1.txt)
[pid_1.txt](https://github.com/deeplearning4j/libnd4j/files/212850/pid_1.txt)

**Comment by agibsonccc** [comment]
This should be fixed with the new tad.
