### ISSUE TITLE
Static Analysis Results

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#118]
I've ran a static analyzer on the code, and tried to annotate the problematic lines in their corresponding commits, so there is a bit of context where it actually came from.

This issue just collects those comments, and where it wasn't possible just mentions them.

# Not-Inline-Commentables
### https://github.com/deeplearning4j/libnd4j/blame/master/include/shape.h#L3536
```
 retOffset = info->offset + sliceIdx;
```
This unconditionally overwrites the retOffset that was set earlier in that function.

-

### https://github.com/deeplearning4j/libnd4j/blame/master/include/shape.h#L4222
Both branches of this if are identical. Is that meant to be like that?

-

### https://github.com/deeplearning4j/libnd4j/blame/master/include/pairwise_transform.h#L1602
```
return d2 - d2;
```
This will always return 0. I guess this is meant to be `d2 - d1`?

-

### https://github.com/deeplearning4j/libnd4j/blob/master/include/summarystatsreduce.h#L998
Both branches are identical. And I don't think this use of OpenMP is performant.

-

### https://github.com/deeplearning4j/libnd4j/blob/master/include/summarystatsreduce.h#L1169
Both branches are identical.

-

### https://github.com/deeplearning4j/libnd4j/blame/master/include/shape.h#L4201
The body of `prod` and `prodLong` are exactly the same. I would guess that `prodLong` should actually return `long`?

# Inline Comments
https://github.com/deeplearning4j/libnd4j/commit/71a706cacb2046e5687ea2e9f4a1250ef8d81ccf#commitcomment-17141719
--
https://github.com/deeplearning4j/libnd4j/commit/71a706cacb2046e5687ea2e9f4a1250ef8d81ccf#commitcomment-17141759
--
https://github.com/deeplearning4j/libnd4j/commit/71a706cacb2046e5687ea2e9f4a1250ef8d81ccf#commitcomment-17141767
--
https://github.com/deeplearning4j/libnd4j/commit/2b2d264f04e0cd68f079757a74f9246acbbf2252#commitcomment-17141804
--
https://github.com/deeplearning4j/libnd4j/commit/ef2b2a8ed974fca3baef874660be12e7f663decd#commitcomment-17141917
--
https://github.com/deeplearning4j/libnd4j/commit/bbde680a057fb7e28f298bccc096b7f357d0e81d#commitcomment-17142017
--
https://github.com/deeplearning4j/libnd4j/commit/653b6bbde350819cd29a1708089f8d0dcf4dab00#commitcomment-17142065
--
https://github.com/deeplearning4j/libnd4j/commit/e0e2560b77e9964a7d07b1cc2726303ed01600b4#commitcomment-17142476
--
https://github.com/deeplearning4j/libnd4j/commit/e0e2560b77e9964a7d07b1cc2726303ed01600b4#commitcomment-17142480
--
https://github.com/deeplearning4j/libnd4j/commit/b585c5ade1ed9cb8f2d3eaf7d3f7d2d4dda94a89#commitcomment-17142593
--

**Comment by agibsonccc** [comment]
Re run this?

**Comment by treo** [comment]
Most of this is fixed in https://github.com/deeplearning4j/libnd4j/pull/148 everything else (that seems to be actually important) has its own issue now.
