### ISSUE TITLE
Cuda: IllegalStateException: MemcpyAsync failed

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/libnd4j#128]
#### System Setup
* Windows 10 64bit
* libnd4j and nd4j compile from current master
* GeForce 970M GTX

#### What I did
Tried to learn a 3 layer convolution network. 

#### Full output:
https://gist.github.com/andreas-eberle/5089708e2b0dbac8ebf33176011a1d3a

**Comment by agibsonccc** [comment]
Is this still happening?

**Comment by andreas-eberle** [comment]
I cannot reproduce it any more. Seams to be fixed.
