### ISSUE TITLE
libnd4j crashes.

### ISSUE THREAD

**Issue by kaimast** [deeplearning4j/libnd4j#129]
Here's the error log of the problem I have been trying to fix last week.  I am not really sure what causes it.

[hs_err_pid6806.txt](https://github.com/deeplearning4j/libnd4j/files/230505/hs_err_pid6806.txt)

**Comment by saudet** [comment]
It's a SIGILL. That means it's trying to execute an illegal instruction. Maybe GCC isn't able to detect the capabilities of your CPU properly. Try to remove "-march=native" option from the `CMakeLists.txt` file and let's see what that gives.

**Comment by agibsonccc** [comment]
Updates on this?
