### ISSUE TITLE
dl4j-0.4-examples causes runtime errors on POWER with GPGPU

### ISSUE THREAD

**Issue by negiyas** [deeplearning4j/libnd4j#130]
2016/05/02 Update status
I have tried the latest version from git. It still causes the following errors.
https://gist.github.com/negiyas/f6d24888b648ee3f35647b7befc6025d
-----------------------------------------------------------------------------------------------------------------------------
2016/04/22 Update status
I have pulled the latest version from git, and run the dl4j-0.4-example again.
The situation has been changed. Although the program outputs "NaN" as score, but it continues to run until timeout of job scheduler. 
**_Error log:_**
https://gist.github.com/negiyas/02a643a09b9495e2f2324d9e2e15231c
-----------------------------------------------------------------------------------------------------------------------------
2016/04/22 Initial issue
When we run dl4j-0.4-examples on POWER processor with GPGPU, the program outputs the following runtime errors, and stops abnormally.
**_Error log:_**
https://gist.github.com/negiyas/0c32c850f70da86c655a521c0aca5530
-----------------------------------------------------------------------------------------------------------------------------
**_Other Info._**
$ uname -a
Linux tulgbfen1 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:10:52 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "Tesla K40m"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 11520 MBytes (12079136768 bytes)
  (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
  GPU Max Clock rate:                            876 MHz (0.88 GHz)
  Memory Clock rate:                             3004 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   2 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "Tesla K40m"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 11520 MBytes (12079136768 bytes)
  (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
  GPU Max Clock rate:                            876 MHz (0.88 GHz)
  Memory Clock rate:                             3004 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   6 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from Tesla K40m (GPU0) -> Tesla K40m (GPU1) : No
> Peer access from Tesla K40m (GPU1) -> Tesla K40m (GPU0) : No

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 2, Device0 = Tesla K40m, Device1 = Tesla K40m
Result = PASS

**Comment by agibsonccc** [comment]
Update on this?

**Comment by negiyas** [comment]
Thank you. I have updated
https://github.com/deeplearning4j/libnd4j/issues/130 .
The latest version still cases the following errors. Can you look at them?

https://gist.github.com/negiyas/f6d24888b648ee3f35647b7befc6025d

Sincerely,
Yasu

Yasushi NEGISHI,
Deep Computing & Analytics, Computing as a Service, IBM Research - Tokyo

**Comment by agibsonccc** [comment]
Could you try again? That was a java error not related to the gpu. I just tested it and that error is gone now.

**Comment by negiyas** [comment]
Sure. I will.

Sincerely,
Yasu

Yasushi NEGISHI,
Deep Computing & Analytics, Computing as a Service, IBM Research - Tokyo

**Comment by agibsonccc** [comment]
Closing this. We've been running on power for a while. I'd say let's aim for benchmarks next.

**Comment by negiyas** [comment]
Thank you, but this issue has not been solved in our environments.

I tried the latest code in our environments.
It is still running, but it does not seems be converged.
I have two machines, and the situation is the same on the both machines.

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DeepLearning4j Examples 0.4-rc0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ deeplearning4j-examples ---
o.d.e.c.LenetMnistExample - Load data....


o.d.e.c.LenetMnistExample - Build model....
o.d.e.c.LenetMnistExample - Train model....
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 3.0154978765771023
o.d.o.l.ScoreIterationListener - Score at iteration 1 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 2 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 3 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 4 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 5 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 6 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 7 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 8 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 9 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 10 is NaN

**Comment by agibsonccc** [comment]
Right but nothing specific to power here. Please open issues for related things after this has been closed:
https://github.com/deeplearning4j/nd4j/issues/884

Subscribe to that issue and you will know when to test further. Thanks!
