### ISSUE TITLE
SoftmaxDerivative Execution Crash

### ISSUE THREAD

**Issue by newikov** [deeplearning4j/libnd4j#132]
Crashes on the SoftmaxDerivative execution. Same code works for Sigmoid, Softmax, etc. 

INDArray input = Nd4j.create(new double[]{ -1.07, -0.01, 0.45, 0.95, 0.45, 0.16, 0.20, 0.80, 0.89, 0.25}).transpose();
INDArray output = Nd4j.create(10,1); 
Nd4j.getExecutioner().exec(new SoftMaxDerivative(input, output));   

https://gist.github.com/newikov/9ea12264ba808c832c37decdb8689f63

**Comment by agibsonccc** [comment]
Not seeing with latest changes:
https://github.com/deeplearning4j/nd4j/pull/854
