### ISSUE TITLE
Usage of shape::prodLong

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#149]
From the name of the function, I would guess that it should produce a `long` type answer. From its usage, it isn't that clear though. 

In `array.h` it is always used in such a way, as to create `Nd4jIndex`, in `shape.h` it is often used to create an `int`.

If it gets data that on multiplication creates results larger than int, it will wrap around, and probably cause confusion why it did so. I would guess that it should be used as an `Nd4jIndex` everywhere.

**Comment by agibsonccc** [comment]
This is more about us needing type consistency. Feel free to open up a new issue consolidating Nd4jIndex/int
