### ISSUE TITLE
CPU Performance regression

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#151]
I have a Model which used to train quite fast. Running it with unified_shared_memory yields the following from the profiler. Current master isn't better either.

![snapshot](https://files.gitter.im/deeplearning4j/deeplearning4j/earlyadopters/Xa2q/blob)
![hotspots](https://files.gitter.im/deeplearning4j/deeplearning4j/earlyadopters/Jmbk/blob)

This is the code that is calling all of it.
```java
    public DataSet transform(String text, String label, List<String> labels) {
        INDArray features = Nd4j.create(new int[]{1, lookupTable.layerSize()});
        Tokenizer tokenizer = tokenizerFactory.create(text);
        int num = 0;
        while(tokenizer.hasMoreTokens()){
            String token = tokenizer.nextToken();
            if(vocab.containsWord(token)){
                num++;
                features.addi(lookupTable.vector(token));
            }
        }
        features.divi(num);

        INDArray labelArray = Nd4j.create(labels.size());
        labelArray.putScalar(labels.indexOf(label), 1.0);
        return new DataSet(features, labelArray);
    }
```

**Comment by treo** [comment]
I've poked the problem some more, coming from a different perspective. I was trying to train word vectors, and the performance was frankly horrible. On a 36 core machine, it was slower then on my desktop, while 3.8 runs perfectly fine on it (using all 36 cores!).

So, I've started looking at the profiler for that, and found that in the about 25 seconds, it allocates 14.5 million buffers, 2/3 of them being IntBuffer and 1/3 being FloatBuffer. 

Pretty much all of the FloatBuffers being created from calls to `BaseNDArray.slice` and all of the IntBuffers are created by calls to `Shape.shapeOf` (which in turn are also indirectly called by `BaseNDArray.slice`).

All this short lived array creation in turn forces the JavaCPP garbage Collection to work very hard, and as it seems to happen at array creation time, it makes the problem even worse.

So, I have some suggestions as to what may be worthwhile solutions:

1. Focused to the problem at hand: Simply Reuse the already available rank and shape in `NDArrayIndex.resolve`. That alone will cut the IntBuffer creation in half. 
2. Reduce the useless Buffer creation. I don't see any reason why creating a Buffer is preferred over using simple java arrays while staying 100% on the JVM, all it does is double the GC cost and kill any hope that the JIT may do anything useful.
3. Make JavaCPP garbage collection asynchronous.

@agibsonccc @saudet what do you think?

**Comment by treo** [comment]
When running with `-XX:+UseConcMarkSweepGC` the main hot spot is `deallocateReferences` 
![image](https://cloud.githubusercontent.com/assets/509379/14937432/7d9b7ba4-0f07-11e6-9f4c-6e5c67ff8f1b.png)

So this looks pretty much like it requires a different GC solution for JavaCPP.

**Comment by saudet** [comment]
This is on Windows right? I'm pretty sure this is in part the same issue as https://github.com/deeplearning4j/nd4j/issues/768

NIO buffers are pretty expensive to allocate, so they should be cached, but they are not always for a reason I'm not sure I understand, @AlexDBlack @agibsonccc ?

**Comment by agibsonccc** [comment]
We got rid of the to toNioInt calls though

**Comment by saudet** [comment]
Right, so how does it look now? Is allocation still a hot spot?

**Comment by treo** [comment]
While better now, it still isn't great:
![image](https://cloud.githubusercontent.com/assets/509379/14951543/04c69f5c-105a-11e6-8e9d-6af88156ab9b.png)

But at least the deallocateReferences call went away :)

Also I can see this behavior with both, the standard windows allocator and jemalloc, only that with jemalloc allocateArray takes the first place.

**Comment by saudet** [comment]
Thanks! So 14.5 million calls in 25 s, 1.7 us per allocation. That sounds about right. If we added some caching to nd4j to reuse preallocated NDArray objects, we might be able to reduce that by a factor of ten...

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/899

**Comment by treo** [comment]
You have got rid of the `asNio` calls, but allocation / deallocation is still a problem.

![Uploading profiler.png…]()

**Comment by agibsonccc** [comment]
That's @saudet then.

**Comment by saudet** [comment]
Let's wait and see how much caching helps with that first...

**Comment by raver119** [comment]
Is this issue still actual after all applied changes? @treo

**Comment by treo** [comment]
The core problem I raised here is fixed by now.
