### ISSUE TITLE
Java fatal error SIGFPE during training

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/libnd4j#153]
*Migrated from https://github.com/deeplearning4j/nd4j/issues/869*

While training a convolutional net using a dataset of <10,000 black and white JPEGs,  I encountered a fatal error while training my net using Spark `1.6.1`:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x000000012a82c8ba, pid=32002, tid=76291
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x278ba]  _ZN5shape8ind2subCEiPiii+0x8a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

Application output is here: https://gist.github.com/crockpotveggies/8fdcaa59224a25b62f6d237a8c2120c3

~~This is the configuration of my convolutional neural net: https://gist.github.com/crockpotveggies/d342bbb8a614fc88286bb8e75a8454e1~~

**I've uploaded a repo for reproducibility.** Use a dataset of <10,000 black and white images 100x100 dimensions, total of 8 labels. You can find it here: https://github.com/crockpotveggies/libnd4j-SIGFPE-error

**Comment by agibsonccc** [comment]
Re run?

**Comment by crockpotveggies** [comment]
Latest pull resulted in the following error, will have to resolve that before getting a definite answer on this:
```
INFO  [2016-05-05 22:07:03,162] org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer: Starting early stopping training
WARN  [2016-05-05 22:07:08,207] org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer: Early stopping training terminated due to exception at epoch 0, iteration 0
! java.lang.IllegalStateException: Mis matched shapes
! at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:38) ~[nd4j-api-0.4-rc3.9-SNAPSHOT.jar:na]
```

**Comment by agibsonccc** [comment]
Is this possibly a race condition? The culpri is related to the labels it looks like ;/

**Comment by crockpotveggies** [comment]
I've been running this in standalone mode (no Apache Spark) so I'm unsure if it's a race condition. Is anything parallelized with Canova that would cause training to fire up before it's finished?

**Comment by agibsonccc** [comment]
Is this still the case?

**Comment by crockpotveggies** [comment]
This no longer happens using JVM 8 and can be removed.
