### ISSUE TITLE
.putScalar very slow

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#157]
I've just finished my binary word vector loader, and on rc3.8 it is bottlenecked by `.putScalar`, which consumes 51% of the time.

Trying to run it with rc3.9, it is an even worse bottleneck, taking up more than 90% of the time.

![image](https://cloud.githubusercontent.com/assets/509379/14944810/c7156364-0fff-11e6-91f4-149202f6c457.png)

Part of it is probably related to https://github.com/deeplearning4j/libnd4j/issues/151 but it also looks like a lot of work is unnecessarily repeated there.

**Comment by AlexDBlack** [comment]
Can you give me something I can run to reproduce this?
Also fyi there were some putScalar imprevements here (https://github.com/deeplearning4j/nd4j/pull/871) but they probably aren't being used.
Also the .asNioInt() stuff should have been removed already I thought.

**Comment by treo** [comment]
You can reproduce it with https://gist.github.com/treo/2947b21a55c1b175ac5ed24a8673924d.
My word vectors file is a bit too large to share (5.3GB). But you can easily take any text word vector file that is created with dl4j and convert it to binary format.

**Comment by treo** [comment]
I've revisited this, and by using the new specialized interface it works as fast as it is supposed to, but as I'm switching between rc3.8 and rc3.9 so I can't use the optimized interface.

Instead I propose to use it automatically: https://github.com/deeplearning4j/nd4j/pull/881

And for the cases to use the specialized `getOffset(shapeInformation, indexes)` method instead of calling shape() and stride().

**Comment by agibsonccc** [comment]
Re run this? I got rid of the shapeInfo() calls and migrated them to data buffer.

**Comment by treo** [comment]
This was already pretty good after you merged my pull request. Now, when loading my binary w2v file, all of the dl4j methods combined are only responsible for about 1% of the time :)

**Comment by treo** [comment]
I'm reopening this, because putScalar is slow once again:
![image](https://cloud.githubusercontent.com/assets/509379/15196870/bf006c38-17ce-11e6-8ef4-f53e31144ba8.png)

**Comment by AlexDBlack** [comment]
Hm, the rank() calls are used for input validation.
There's a rank field in BaseNDArray, so switching to that (rather than extracting it from the buffer every time) should fix this.
https://github.com/deeplearning4j/nd4j/blob/3613ff18abcd816a36a6f7d9ac43effc2b2dbedb/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L94

**Comment by AlexDBlack** [comment]
Another thought/option: we add some 'sizeUnsafe()' and 'strideUnsafe()' type methods, without input validation.

**Comment by agibsonccc** [comment]
Update on this?

**Comment by treo** [comment]
It is still slow, and is one of the reasons why dropout is such a big performance hit currently.

**Comment by mjakobus** [comment]
I opened a ticket for the dropout performance problem in deeplearning4j [deeplearning4f#1562](https://github.com/deeplearning4j/deeplearning4j/issues/1562). Didn't knew about this ticket here. So my ticket is probably a duplicate.

**Comment by AlexDBlack** [comment]
Some optimizations:
https://github.com/deeplearning4j/nd4j/pull/975

On the following tests (100M putScalars on 2d and 4d arrays): https://gist.github.com/AlexDBlack/2f59c2c1608524575bacb8621adb60b9

2d:     8799 -> 5236ms     (19.1M/sec)
4d:     20089 -> 8957ms   (11.1M/sec)

![image](https://cloud.githubusercontent.com/assets/2360237/15571717/cddacc14-237f-11e6-87e9-b5e1460a0631.png)
(That's all Shape.sizeUnsafe and Shape.strideUnsafe methods)

At this point: if we want better performance on putScalar, I think we'll need to go back to using an int[] fields (shape, stride) in BaseNDArray. We could always initialize these lazily - i.e., extract it if (and only if) we need them, and then cache them if required.

**Comment by saudet** [comment]
If we ever only read ints from the buffer, using IntBuffer is probably going to be faster than ByteBuffer, and probably as fast as int[].

**Comment by saudet** [comment]
I've looked a bit more at this, and `BaseDataBuffer.getInt(long)` looks suspicious to me:
```java
    @Override
    public int getInt(long ix) {
        return (int) getDouble(ix);
    }
```
I don't think we would need `getDouble()` and a conversion like that there, but maybe I'm missing something?

**Comment by AlexDBlack** [comment]
Right, as long as we handle the different cases properly (int from float data, etc) then there's no need to do the getDouble + conversion, afaik.

**Comment by agibsonccc** [comment]
Right so I did that originally to prevent me from having to rewrite all the
conversion logic...casting shouldn't be THAT expensive though?

**Comment by saudet** [comment]
@agibsonccc I guess we'll find out pretty soon, I've added a proper `getInt()` along with the rest of the changes in this PR: https://github.com/deeplearning4j/nd4j/pull/1014  Merge it if it looks alright
