### ISSUE TITLE
nd4j-native sum performance

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#158]
(Relocation of https://github.com/deeplearning4j/nd4j/issues/735)

Running this code:

``` java
int n = 100000;
        int repeats = 10000;

        double[] arrJava = new double[n];
        INDArray arrND = Nd4j.create(n);

        for (int i = 0; i < n; i++) {
            arrJava[i] = i;
            arrND.putScalar(i, i);
        }

        System.out.println("double[]...");
        long time = System.currentTimeMillis();
        int sum;
        for (int i = 0; i < repeats; i++) {
            sum = 0;
            for (int j = 0; j < n; j++) {
                sum += arrJava[j];
            }

            if (sum == 0) {
                System.out.println("should never happen - here to stop jit from optimizing away this code");
            }
        }
        System.out.println("time: " + (System.currentTimeMillis() - time));

        System.out.println("NDArray...");
        time = System.currentTimeMillis();
        double dSum = 0.0;
        for (int i=0; i<repeats; i++) {
            dSum = arrND.sumNumber().doubleValue();
            if (dSum == 0) {
                System.out.println("should never happen - here to stop jit from optimizing away this code");
            }
        }
        System.out.println("time: " + (System.currentTimeMillis() - time));
```

with a single thread (OMP_NUM_THREADS=1) I get

```
double[]...
time: 3969
NDArray...
time: 5299
```

While with 8 Threads I get:

```
double[]...
time: 3879
NDArray...
time: 1721
```

So I'd say, while the 8 Threaded version is faster than the single threaded, the single threaded version should not be slower than the also single threaded pure java version.

**Comment by agibsonccc** [comment]
I mean...you tell me: https://github.com/deeplearning4j/libnd4j/blob/c2c49fb78efaeb3be7c26a41c3bf263d276c26a4/include/reduce.h#L535 it's a for loop with simd above it. I'm not sure what else to do here.

**Comment by saudet** [comment]
This is probably caused by the use of virtual C++ functions. The compiler won't be able to vectorize over that.

**Comment by treo** [comment]
This has a size of 100k, so it isn't going through the 8k optimization. But even when it goes through it (n=7999), it is still ~ 2x slower than the pure java version.

I'm not really sure what to do about it. I'd guess that @saudet is right here. I thought that maybe adding a `#pragma omp declare simd` on the op and update methods might help, but that apparently didn't help at all.

I'd guess that to get all the benefits of full vectorization, the code would have to be written differently, with explicit information for the compiler.

**Comment by saudet** [comment]
We can think about that after the release, but would it be possible to rewrite these kinds of loops into a call like `local = opUpdate(local, x, length, extraParams)` and inside `opUdate()`, we might have something like the following?
```
#pragma omp simd
for (Nd4jIndex i = 0; i < length; i++) {
    local += x[i];
}
return local;
```
That ought to make things crazy fast.

**Comment by treo** [comment]
Yes, I think that is something for rc3.10 :), the issue should live on, so we don't forget about it.

I like your idea. From what I understand the op doesn't change, over the loop, so putting the calculation loop inside an op+update method, should allow us to go even none step further:
```c
#pragma omp simd reduction(+:local)
for (Nd4jIndex i = 0; i < length; i++) {
    local = local + x[i];
}
return local;
```
If we were to go even more crazy, i.e. push the whole loop inside the op, it would be possible to give this reduction information to openmp multi threading, so it would end up knowing how to reduce in parallel.

I haven't put enough thought into it to know how it would affect maintainability or how much that would affect cuda. But I do think that there should be some complexety budget left over, after cleaning up libnd4j a bit.

**Comment by treo** [comment]
So... actually the results here are looking better than they actually are, because of a slight oversight in the benchmarking code:
```java
 int sum; // <-- This forces java to do type conversion on each step 
```
So after fixing this and making it so that the java jit can work its magic, it beats nd4j by even a larger margin
```
double[]...
time: 877
```

Java does have the advantage that the JIT can work its magic and basically compile the code down to compute it very efficiently, and beating that efficiency isn't easy. As it can really optimize that very simple loop.

So I went ahead and broke libnd4j for everything but this single benchmark, in order to try out what we can do.

First I replaced [reduce.h#L535](https://github.com/deeplearning4j/libnd4j/blob/c2c49fb78efaeb3be7c26a41c3bf263d276c26a4/include/reduce.h#L535) with this (as I said, it breaks libnd4j for everything but this single benchmark):
```c
#pragma omp parallel for simd reduction(+:local)
for (Nd4jIndex i = 0; i < length; i++) {
    local = local + x[i];
}
```

Which on one core is already about 2.5x faster than our old numbers:
```
NDArray...
time: 2107
```
But still, more then 2x slower than the fixed double iteration.

Now, allowing it to use all my cores and hyperthreads (i.e. using 8 threads) I can get it down to:
```
NDArray...
time: 649
```
Which is at least 1,35x faster, but also uses 8 threads. On the other hand this is also 2x faster than the unoptimized version. 

So for very tight loops beating out java jit is a pretty tall order, and can probably only be achieved by even more trickery.

But in the real world not everything can be optimized this well by the JIT. And this is where nd4j should be able to really shine.

I think that it would be worthwhile to rethink some of the code structure for rc3.10 in order to make full use of automatic vectorisation.

**Comment by saudet** [comment]
Yes, it's often easy to get good enough performance with Java code:
http://bytedeco.org/news/2014/12/23/third-release/
That's why some people prefer that to Python :) For others its Lua:
http://bytedeco.org/news/2015/03/14/java-meets-caffe/
And more recently Julia, but multithreading is just an afterthought on those platforms... 
Java isn't going anywhere.

**Comment by treo** [comment]
This can be considered fixed when https://github.com/deeplearning4j/libnd4j/pull/222 is merged.

Using n = 100000:
```
double[]...
time: 873
NDArray...
time: 234 // OMP_NUM_THREADS=1
NDArray...
time: 384 // OMP_NUM_THREADS=4
```

Using n = 1000000:
```
double[]...
time: 8820
NDArray...
time: 1228 // OMP_NUM_THREADS=1
NDArray...
time: 629 // OMP_NUM_THREADS=4
```

**Comment by raver119** [comment]
Nope. It's not fixed yet. On next iteration we should have reduction stuff done properly, according to OpenMP 4

**Comment by raver119** [comment]
I mean: yes, current iteration makes cpu things better. But it's not the end yet.
