### ISSUE TITLE
CNN's spend most of their time on .assign / tensorMmul

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#159]
Running LenetMnistExample, most of the time is spent on calls of `.assign`.

![image](https://cloud.githubusercontent.com/assets/509379/14949263/e495e6fe-1048-11e6-995b-be129a017aeb.png)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/blob/c4b7b4e6b4bc6e4bf4fa6092e43b177bdcf99129/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L688-L688

Re run benchmarks?

**Comment by treo** [comment]
Looks pretty much unchanged

**Comment by AlexDBlack** [comment]
Confirmed. TensorMmul is still hitting the reshape-with-copy condition after recent changes.

**Comment by AlexDBlack** [comment]
Complete rewrite of CNN functionality here: https://github.com/deeplearning4j/deeplearning4j/pull/1539
