### ISSUE TITLE
Add rpm/deb builds

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#169]
CMake has a nice plugin for doing rpm/deb files. This will allow us to deploy things to public repositories for easier installation purposes while also allowing us to leverage some build automation as well as containers.
https://schneide.wordpress.com/2013/02/11/build-a-rpm-package-using-cmake/

**Comment by huitseeker** [comment]
See also https://github.com/deeplearning4j/nd4j/issues/1678
