### ISSUE TITLE
CPU utilization for down to 50~% when training FFN. Was 100% last week.

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/libnd4j#174]
After I pulled yesterday the CPU utilization during training is way down from what it was last week. I do not have any benches on actual training time, though.

I'm using MKL on Windows 10 with:

- MKL_DYNAMIC=FALSE
- MKL_NUM_THREADS=8 (same as my logical count)

Here's some screenshots to show what's going on:

- Hotspots: https://files.gitter.im/deeplearning4j/deeplearning4j/earlyadopters/B40C/blob
- Heap: https://files.gitter.im/deeplearning4j/deeplearning4j/earlyadopters/8jdD/blob
- CPU: https://files.gitter.im/deeplearning4j/deeplearning4j/earlyadopters/S7NL/blob

**Comment by agibsonccc** [comment]
Curious if you could also run the same with openblas?

**Comment by treo** [comment]
Could you also please add a screenshot of the backtraces for your hotspots (i.e. what calls all the array allocation?)

**Comment by Habitats** [comment]
![capture](https://cloud.githubusercontent.com/assets/1082096/15107281/339d8d7a-15cf-11e6-801f-3b6c9c7b0330.PNG)

**Comment by agibsonccc** [comment]
That looks like you using add() rather than addi. That isn't us. Try using the inplace version first.

It'd be one thing if that was our code but that's all you.

**Comment by Habitats** [comment]
Alright, so using inplace lead to faster training, but the CPU utilization remains the same. I will try and do a better benchmark later.

**Comment by Habitats** [comment]
Alright; cached the doc vec calculations causing this. It's fast again now. Closing.
