### ISSUE TITLE
Documentation: dependency list

### ISSUE THREAD

**Issue by mschaars** [deeplearning4j/libnd4j#176]
The current guide for macosx (https://github.com/deeplearning4j/libnd4j/blob/master/macOSx10%20(CPU%20only).md)

does not explicitly say that javacpp needs to be pulled. Ideally, there should be some checklist that says what needs to be pulled before commencing installation.

**Comment by mschaars** [comment]
Also needs to specifically say that it has to be this javacpp https://github.com/bytedeco/javacpp.git, not the fork in dl4j

**Comment by treo** [comment]
fixed in 59e3c22b63c861c0f711fcb87214cbf3232ad490
