### ISSUE TITLE
nd4j-native: Broadcast/reduce along dimension ops slow(er) for imbalanced arrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#204]
Consider the following simple test:
https://gist.github.com/AlexDBlack/4a79db84f9f355664d2499427bea2f95

Rows: 2048, columns: 2048, total elements = 4194304
gemm:     46591
addi:     844
addiRow:  1537
relu:     672
max(1):   1533
IsMax(1): 931
Rows: 4096, columns: 1024, total elements = 4194304
gemm:     23678
addi:     837
addiRow:  1726
relu:     622
max(1):   1730
IsMax(1): 1139
Rows: 32768, columns: 128, total elements = 4194304
gemm:     3874
addi:     831
addiRow:  5083
relu:     608
max(1):   4974
IsMax(1): 4272

Some observations here:
- All operations (excluding mmul) have the same number of elements; in terms of big-O complexity, all 3 test cases should have about the same runtime
- For imbalanced arrays, max/addiRow/isMax are all way slower. I assume this is due to tensor offset calculation or something?
- max(1) takes longer than isMax(1)?? This isn't at all expected. Only thing I can assume is the output value offset calculation is an issue, or that we've got an issue with false sharing on the output array.

**Comment by raver119** [comment]
Is this still an issue with current nd4j/libnd4j masters? Latest changes greately affected broadcasts.

However reduce changes are still pending...

**Comment by AlexDBlack** [comment]
Rerunning these tests on nd4j/libnd4j master:

Rows: 2048, columns: 2048, total elements = 4194304
gemm:     43991
addi:     726
addiRow:  413
relu:     429
max(1):   360
IsMax(1): 966
Rows: 4096, columns: 1024, total elements = 4194304
gemm:     23780
addi:     709
addiRow:  394
relu:     417
max(1):   331
IsMax(1): 1182
Rows: 32768, columns: 128, total elements = 4194304
gemm:     3580
addi:     708
addiRow:  397
relu:     415
max(1):   387
IsMax(1): 4368


Decent speedup on most things. :)
But what's up with addi > addiRowVector? Maybe row vector fitting in l1 cache, hence less memory access?

**Comment by raver119** [comment]
I wonder, if that's still an issue?

**Comment by AlexDBlack** [comment]
I guess not - I just re-ran this, looks pretty  good to me :)

```
Rows: 2048, columns: 2048, total elements = 4194304
gemm:     27398
addi:     518
addiRow:  128
relu:     115
max(1):   251
IsMax(1): 328
Rows: 4096, columns: 1024, total elements = 4194304
gemm:     13220
addi:     495
addiRow:  118
relu:     101
max(1):   234
IsMax(1): 365
Rows: 32768, columns: 128, total elements = 4194304
gemm:     2084
addi:     495
addiRow:  120
relu:     125
max(1):   244
IsMax(1): 324
```
