### ISSUE TITLE
Make compute code specifiable from the command line

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#212]
The shell script for building should look for a compute code environment variable and allow overriding where possible. This will make it possible to build for only 1 target architecture resulting in faster compilation times.

**Comment by saudet** [comment]
There's a patch for `FindCUDA.cmake` that does that, but never made it into CMake here:
https://cmake.org/Bug/view.php?id=11767

**Comment by agibsonccc** [comment]
We could put it in our cmake distro with libnd4j.
