### ISSUE TITLE
JVM hangs on loading CUDA Version of nd4j.dll

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#22]
I have build the Cuda Version of libnd4j like described in https://github.com/treo/libnd4j/blob/windows-docs-improvement/windows.md

But when I try to use it, the JVM completely hangs. 

I have narrowed down the problem to actually loading nd4j.dll, so it can be tested directly after building libnd4j:

```java
public class App 
{
    public static void main( String[] args )
    {
        System.loadLibrary("nd4j"); // needs nd4j to be on the PATH
    }
}
```

This happens only with the CUDA build, the CPU build loads fine.

I have verified that CUDA itself works on my system by building and running several of the examples included in the CUDA Toolkit.

**Comment by devlop16** [comment]
I replicate the issue too

**Comment by treo** [comment]
I have attached a debugger to the JVM and it appears the hang occurs on calling cudaMalloc. Somewhere deep in nvcuda.dll (a driver file) it keeps looping, but I can't figure out why.

That's the call stack for it:

```
 	nvcuda.dll!00007ffb6d899988()	Unknown
 	nvcuda.dll!00007ffb6d8996aa()	Unknown
 	nvcuda.dll!00007ffb6d897b9e()	Unknown
 	nvcuda.dll!00007ffb6d897add()	Unknown
 	nvcuda.dll!00007ffb6d896a3b()	Unknown
 	nvcuda.dll!00007ffb6d896743()	Unknown
 	nvcuda.dll!00007ffb6d836104()	Unknown
 	nvcuda.dll!00007ffb6d83091e()	Unknown
 	nvcuda.dll!00007ffb6d814305()	Unknown
 	nvcuda.dll!00007ffb6d7f50c5()	Unknown
 	[External Code]	
 	nd4j.dll!nd4j::buffer::createBuffer<int>(int * data, int length) Line 239	C++
	nd4j.dll!ScalarShapeInformation::ScalarShapeInformation() Line 83	C++
 	nd4j.dll!`dynamic initializer for 'ScalarInfo<double>::shapeInfo''() Line 166	C++
 	[External Code]	
 	jvm.dll!0000000057f77758()	Unknown
 	jvm.dll!0000000057e68b0a()	Unknown
 	java.dll!0000000057cb234f()	Unknown
 	[External Code]
```

**Comment by treo** [comment]
With the current version of the windows branch this problem doesn't happen any more. Probably because the offending code (as seen in the stacktrace) was removed.
