### ISSUE TITLE
Unable to build on Windows 7

### ISSUE THREAD

**Issue by alderucci** [deeplearning4j/libnd4j#230]
I followed the instructions on https://github.com/deeplearning4j/libnd4j/blob/master/windows.md

But when I run
./buildnativeoperations.sh

It returns the following error:
CMake Error at /usr/share/cmake-3.3.2/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/cygdrive/c/msys64/mingw64/bin/c++.exe" is not able to
  compile a simple test program.

  It fails with the following output:

   Change Dir: /home/libnd4j-master/blasbuild/cpu/CMakeFiles/CMakeTmp

**Comment by treo** [comment]
This looks pretty much like you aren't using msys2?

**Comment by saudet** [comment]
Or it's picking up an already installed Cygwin. It should be uninstalled...

**Comment by alderucci** [comment]
Actually I did use msys2 just as it says in the instructions on  https://github.com/deeplearning4j/libnd4j/blob/master/windows.md.

I also did not have a previous installation of cygwin on my computer.

**Comment by saudet** [comment]
I wonder why it tries to access "cygdrive", which obviously doesn't exist. Are you sure it is calling the CMake version that comes with MSYS2 and *not* one installed using the Windows installer?

**Comment by alderucci** [comment]
Unfortunately I don't understand unix shell scripts, so I don't know which CMake the script buildnativeoperations.sh is running.

**Comment by saudet** [comment]
What's the output of `which cmake`?

**Comment by alderucci** [comment]
The output of 'which cmake' is /usr/bin/cmake

**Comment by saudet** [comment]
Looks alright, but "/cygdrive" just doesn't exist on recent versions of MSYS2, so you'll need to figure out why it's trying to use old software...
