### ISSUE TITLE
no jnind4j in java.library.path

### ISSUE THREAD

**Issue by snjagadale** [deeplearning4j/libnd4j#232]
Hardware - Power , Ubuntu 14.04 Linux. 

I have created ubar jar on for https://github.com/deeplearning4j/dl4j-0.4-examples
Then trying to run (./runallexamples.sh) on different system (build uber on different power hardware - same configuration) and following error 
--------------
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1889)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
------------- 

I found similar issue with one of user - https://github.com/deeplearning4j/libnd4j/issues/225
So I have modified pom.xml as per suggestion but its not working. 
modification in pom.xml is as follows. 
+         <dependency>
+            <groupId>org.nd4j</groupId>
+            <artifactId>nd4j-native</artifactId>
+            <version>${nd4j.version}</version>
+            <classifier>linux-ppc64le</classifier>
+        </dependency>
         <dependency>
             <groupId>org.nd4j</groupId>
             <artifactId>${nd4j.backend}</artifactId>
+           <version>${nd4j.version}</version>
         </dependency>
-------

Please let me know how should I proceed for this issue. 
As of now I may prefer to use libnd4j.so and libjnind4j.so through LD_LIBRARY_PATH to go ahead but fix for above issue will be appreciated.

**Comment by saudet** [comment]
The binaries were build with Ubuntu 16.04 because Ubuntu 14.04 doesn't have OpenBLAS. 

@agibsonccc Should we try to get OpenBLAS working on Ubuntu 14.04? Or is it OK to only support 16.04?

**Comment by agibsonccc** [comment]
Let's try to support at least 14.

**Comment by saudet** [comment]
Ubuntu 14.04 on x86_64 works fine, ppc64le is the issue here. GCC is broken on Ubuntu 14.04 for ppc64le, so supporting it might not be that easy. Is it really worth the potential trouble?

**Comment by jagadale** [comment]
We are able to build nd4j and libnd4j on power/ubuntu14.04. 
what issues you had there?
please use this flags - "-O5 –maltivec –ftree-vectorize –ffast-math -mcpu=power8 -mtune=power8 -moptimize-swaps -flto"

**Comment by saudet** [comment]
Thanks! When I tried, `libopenblas-dev` didn't appear to be available, and we get the kind of errors with GCC and anything higher than -O1:
```
/tmp/cc4QBGEy.s: Assembler messages:
/tmp/cc4QBGEy.s:13719: Error: junk at end of line: `8'
/tmp/cc4QBGEy.s:14573: Error: junk at end of line: `8'
```
Has the situation changed since last month? Or is the Docker image "ppc64le/ubuntu:14.04" known to be broken?

**Comment by saudet** [comment]
I see, we need to use `-mcpu=power8` to fix these errors. I'll adjust that in JavaCPP.

For libnd4j itself, could you send a pull request to add the flags above to the CMakeLists.txt file?

**Comment by GZX-ZJU** [comment]
I build the nd4j in Ubuntu 16.04 LTS. I add the nd4j-native-platform 0.6.1-SNAPSHOT dependency, and it reminds me missing linux-ppc64le.jar, windows-x86_64.jar, macosx-x86_64.jar files. But  I can only get the linux-x86_64.jar file. I'm using maven.
