### ISSUE TITLE
compiling with OpenBLAS

### ISSUE THREAD

**Issue by lake4790k** [deeplearning4j/libnd4j#234]
Continuing from https://github.com/deeplearning4j/deeplearning4j/issues/1554:

I think there are two issues with using OpenBLAS (on Linux).

The easy is that nd4j only finds libopenblas.so from /usr to be packaged in the native jar, but OpenBLAS is installed usually in /opt/OpenBLAS. This I could fix by installing OpenBLAS under /usr.

But there is a bigger problem in libnd4j building. [This](https://gist.github.com/lake4790k/8335c76d19e81903925d4481a7e3704a) is my build and it shows OpenBLAS is only partially used. I think the problem is the cmake FindLAPACK uses FindBLAS to find a BLAS, but OpenBLAS is not found by FindBLAS, only by FindOpenBLAS later, so although libopenblas seems to be linked with libnd4j the support is not compiled in. Confusing situation.

So I don't think OpenBLAS could have ever worked with libnd4j...? Not without FindBLAS being able to identify OpenBLAS as a BLAS. Or is there some other way?

I assume @treo you used something else than OpenBLAS for your test? I can build my test fine with the above and it looks as if it used libopenblas, but the performance is still bad as with the maven dependencies.

If this is the case I'm happy to use some other BLAS lib (just coming from torch I had that already), which one would you recommend on Linux?

**Comment by lake4790k** [comment]
@treo says compiling OpenBLAS worked fine for him. Nevertheless my [build output](https://gist.github.com/lake4790k/8335c76d19e81903925d4481a7e3704a) doesn't look right.

**Comment by saudet** [comment]
@lake4790k Try to add "/opt/OpenBLAS/lib/" to the property value here:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/resources/org/bytedeco/javacpp/properties/linux-x86_64-nd4j.properties#L14
It should then bundle the right file and do what you expect here.

**Comment by lake4790k** [comment]
@saudet thx, packaging libopenblas I managed, but I think libnd4j is not getting compiled properly in the first place.

**Comment by saudet** [comment]
libnd4j no longer needs BLAS. ND4J now depends on the build from the JavaCPP Presets for that.
