### ISSUE TITLE
rc3.10: MKL not loaded correctly when on path

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#235]
With rc3.10 release from maven central, libnd4j apparently doesn't load MKL correctly when it is found on the path.

@Mortomes has reported the problem on gitter, and I've seen it myself. I discounted it on my install, as I have pretty messed up PATH contents.

The error shows itself as `Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.` which then shuts down the JVM (i.e. doesn't crash it, but simply halts it). 

It can be worked around by adding `System.loadLibrary("mkl_rt")`.

While having a workaround is nice, it we should find a way to load MKL correctly if it is found.

**Comment by AlexDBlack** [comment]
+1. New Windows 10 install (< 2 days old), with relatively clean path - exact same error. I had assumed this was my setup. The loadLibrary fix also works for me.

**Comment by saudet** [comment]
Should work now. Thanks for the workaround :+1:

**Comment by treo** [comment]
@saudet I finally found the time to check it out. It works fine now :) So you should probably release a new version of javacpp, so this can be included in the next dl4j release.
