### ISSUE TITLE
Trying to use Cuda crashes the JVM

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#24]
Using the current version and this minimal example the JVM crashes for me:

```
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App 
{
    public static void main( String[] args ) throws InterruptedException {
        Nd4j.ones(1);
    }
}
```

[hs_err_pid8524.log.txt](https://github.com/deeplearning4j/libnd4j/files/165493/hs_err_pid8524.log.txt)
[hs_err_pid8556.log.txt](https://github.com/deeplearning4j/libnd4j/files/165494/hs_err_pid8556.log.txt)

**Comment by treo** [comment]
Still now working for me :cry: 

But it looks like the stackframe has changed. See the attached logs.

[hs_err_pid2916.log.txt](https://github.com/deeplearning4j/libnd4j/files/166813/hs_err_pid2916.log.txt)
[hs_err_pid7436.log.txt](https://github.com/deeplearning4j/libnd4j/files/166814/hs_err_pid7436.log.txt)

**Comment by saudet** [comment]
It also crashes in a similar way here on Linux (Fedora 23) with just a `Nd4j.ones(1)`, so it's probably not related to Windows...
[hs_err_pid14814.log.txt](https://github.com/deeplearning4j/libnd4j/files/168599/hs_err_pid14814.log.txt)

**Comment by treo** [comment]
With the most current commits by @raver119 on nd4j (branch jita_cuda_1_1) and here on branch scalar, this crash is fixed.
