### ISSUE TITLE
ND4J on single-board pc

### ISSUE THREAD

**Issue by B10nicMachine** [deeplearning4j/libnd4j#243]
is it possible to run on ND4J single board microcomputers (such as raspberry pi, ODROID-XU4 etc. with ARM architecture) ?

**Comment by saudet** [comment]
Yes, of course. Building from source should work pretty much the same as with linux-x86_64. If you run into issues, just post them here and we'll fix them as they show up.

**Comment by SadatAnwar** [comment]
did you have any luck with this? Its a fun idea I am considering to try out this weekend on my BBB will update if I get around to actually doing it :)

**Comment by B10nicMachine** [comment]
Theoretically, all dolyuno work, but in practice, I could not check it
because of the lack of a single-board computer. For my task, I use my
friend's server.

16 сент. 2016 г. 17:55 пользователь "Sadat Anwar" <notifications@github.com>
написал:

**Comment by dschowta** [comment]
Working till now for the Raspberry PI 2 (Raspbian linux arm 32 bit JVM) with some changes in nd3j and libnd4j. 
The modified codes are here:
https://github.com/dschowta/libnd4j
https://github.com/dschowta/nd4j
The method followed during the building process is updated in README.md 

I hope this helps

**Comment by agibsonccc** [comment]
@dschowta could we maybe get a pull request here?

**Comment by saudet** [comment]
Thanks for the contribution @dschowta ! For those looking for instructions:
https://github.com/deeplearning4j/libnd4j/blob/master/RaspberryPi2.md

**Comment by HKMaster** [comment]
@saudet did anyone succeeded building ND4J for arm7-hf? I have an ODROID XU4 and i still facing errors when building it.
