### ISSUE TITLE
JVM Crashes in libnd4j.dll (CPU)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#25]
I'm using the [current](https://github.com/deeplearning4j/libnd4j/commit/2ba72db852be50e28a809ee96a1e0f060b4809dd) version compiled for CPU on Windows 10, and nd4j using a javacpp snapshot from the original repository.

When running the following code the JVM crashes.
```
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.AutoEncoder;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;



public class Crash {

    public static void main(String[] args) {
        int size = 12000;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(
                        new AutoEncoder.Builder().nIn(size).nOut(2500)
                                .weightInit(WeightInit.XAVIER).lossFunction(LossFunctions.LossFunction.RMSE_XENT)
                                .corruptionLevel(0.1)
                                .build(),
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(2500)
                                .nOut(250)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));


        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 250)));

    }
}

```

See the attached logs and coredump for more information.
[hs_err_pid7616.log.txt](https://github.com/deeplearning4j/libnd4j/files/165029/hs_err_pid7616.log.txt)
[hs_err_pid8096.log.txt](https://github.com/deeplearning4j/libnd4j/files/165032/hs_err_pid8096.log.txt)
[hs_err_pid8924.log.txt](https://github.com/deeplearning4j/libnd4j/files/165033/hs_err_pid8924.log.txt)

[Core Dump for Pid 8096](https://drive.google.com/open?id=0B2DdeIW7mUvaZGlKZ3BMVHJIeFU)

The problem also appears on the StackedAutoEncodeMnistExample by exiting the process:
`Process finished with exit code -1073741819 (0xC0000005)`.

**Comment by saudet** [comment]
It crashes within an OpenMP thread... I wonder if setting the environment variable OMP_NUM_THREADS=1 makes it behaves better?

**Comment by treo** [comment]
I've re-ran it with that env variable set and it crashed again.

[hs_err_pid720.log.txt](https://github.com/deeplearning4j/libnd4j/files/165252/hs_err_pid720.log.txt)

**Comment by treo** [comment]
Retried it today and it still crashes the jvm.

[hs_err_pid6772.log.txt](https://github.com/deeplearning4j/libnd4j/files/166861/hs_err_pid6772.log.txt)

**Comment by treo** [comment]
With the merge of #28 it seems that now other paths trigger this crash as well. One of the attached logs is from the example application, and the other is from a different one. The crash happens in the same place for both.

[hs_err_pid10540.log.txt](https://github.com/deeplearning4j/libnd4j/files/168054/hs_err_pid10540.log.txt)
[hs_err_pid3944.log.txt](https://github.com/deeplearning4j/libnd4j/files/168055/hs_err_pid3944.log.txt)

**Comment by saudet** [comment]
It also crashes in a similar way here on Linux (Fedora 23) with the snippet above, so it's probably not related to Windows...

[hs_err_pid16589.log.txt](https://github.com/deeplearning4j/libnd4j/files/168609/hs_err_pid16589.log.txt)

**Comment by treo** [comment]
Still crashing with that code, but the stackframe hash changed. See attached log.
[hs_err_pid11356.log.txt](https://github.com/deeplearning4j/libnd4j/files/170615/hs_err_pid11356.log.txt)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/666
