### ISSUE TITLE
PairWiseTransform

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/libnd4j#251]
Problematic frame:
C [libnd4j.so+0xe6d38] void functions::pairwise_transforms::PairWiseTransform<float>::execsimdOps::Copy<float >(float, int, float, int, float, int, float*)+0xa48

[err_pid.txt](https://github.com/deeplearning4j/libnd4j/files/380118/err_pid.txt)

**Comment by saudet** [comment]
Would you remember how to reproduce this? If so, please post the steps here :) Thanks

**Comment by raver119** [comment]
That was fixed ages ago :(
