### ISSUE TITLE
org.reflections.Reflections - could not scan file

### ISSUE THREAD

**Issue by jiadongzh** [deeplearning4j/libnd4j#260]
Dear all,

In ubuntu 14.04,  I installed OpenBlas, libnd4j, and nd4j, and wrote a very simple java hello world program as follow:

public static void main(String[] args) throws Exception{
      INDArray arr1 = Nd4j.create(new float[]{1,2,3,4},new int[]{2,2});
}

with the pom.xml dependency:
```
  <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native</artifactId>
      <version>0.5.0</version>
      <classifier>linux-x86_64</classifier>
    </dependency>

```
However, when I run the code by: java -jar hellowword.jar, I got the following messages:

15:19:51.926 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/
jar:file:/home/wode/httest/lib/nd4j-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-native-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-common-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-buffer-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-jackson-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-context-0.5.0.jar!/
15:19:51.951 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
15:19:51.953 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
15:19:51.953 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
15:19:51.953 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
15:19:51.953 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
15:19:51.954 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
15:19:51.954 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
15:19:51.954 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
15:19:51.954 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
15:19:51.954 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
15:19:52.084 [main] INFO  org.reflections.Reflections - Reflections took 156 ms to scan 7 urls, producing 96 keys and 352 values 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bitbeyond.htmind.App.main(App.java:176)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5151)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	... 1 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:178)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5148)
	... 2 more

I have no idea what is wrong with my program. What does it mean that "org.reflections.Reflections - could not scan file"? I searched by google and could not find any solutions. I am sincerely grateful to you for your any help.

thanks
Jason

**Comment by raver119** [comment]
Just ignore reflection messages.

And please provide full pom.xml

**Comment by jiadongzh** [comment]
Dear raver11g,

Thank you very much for your reply.

(1) OS: Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-30-generic x86_64)

(2) App.java
package com.godwom.helloworld;

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class App {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("hello world");
		INDArray arr1 = Nd4j.create(new float[]{1,2,3,4},new int[]{2,2});
		System.out.println(arr1);
	}

}



(3) run the code by: java -jar helloworld-0.0.1.jar, got the messages:

hello world
16:09:06.414 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/
jar:file:/home/wode/httest/lib/nd4j-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-native-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-common-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-buffer-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-jackson-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-context-0.5.0.jar!/
16:09:06.452 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:09:06.453 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:09:06.453 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:09:06.453 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:09:06.454 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:09:06.454 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:09:06.454 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:09:06.454 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:09:06.455 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:09:06.455 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:09:06.626 [main] INFO  org.reflections.Reflections - Reflections took 206 ms to scan 7 urls, producing 96 keys and 352 values 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.godwom.helloworld.App.main(App.java:11)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5151)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	... 1 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:178)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5148)
	... 2 more


(4) Full pom.xml:
[pom.xml.txt](https://github.com/deeplearning4j/libnd4j/files/416938/pom.xml.txt)


thanks again.
Jason

**Comment by raver119** [comment]
Just change your nd4j dependency to this one: 

```
<dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>0.5.0</version>
</dependency>
```

This will work fine for you.

**Comment by jiadongzh** [comment]
When I changed according to your  comment, I got the error message:

java -jar helloworld-0.0.1.jar 
hello world
16:34:55.984 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/
jar:file:/home/wode/httest/lib/nd4j-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-native-api-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-common-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-buffer-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-jackson-0.5.0.jar!/
jar:file:/home/wode/httest/lib/nd4j-context-0.5.0.jar!/
16:34:56.018 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:34:56.020 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgomp.so.1 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:34:56.020 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:34:56.020 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libgfortran.so.3 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:34:56.020 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:34:56.021 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libopenblas.so.0 in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:34:56.021 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:34:56.021 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libnd4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:34:56.021 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner SubTypesScanner
16:34:56.021 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/nativeblas/linux-x86_64/libjnind4j.so in url jar:file:/home/wode/httest/lib/nd4j-native-0.5.0-linux-x86_64.jar!/ with scanner TypeAnnotationsScanner
16:34:56.186 [main] INFO  org.reflections.Reflections - Reflections took 196 ms to scan 7 urls, producing 96 keys and 352 values 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.godwom.helloworld.App.main(App.java:11)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5151)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	... 1 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:178)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5148)
	... 2 more


thanks
jason

**Comment by jiadongzh** [comment]
Another question:

After I complied the libnd4j, which directory should I put it such that nd4j can find it.

thanks,
jason

**Comment by raver119** [comment]
Please ensure maven was updated & not using caches, because i've manually created new project with exactly the same pom.xml and it's working for me.

**Comment by raver119** [comment]
Also, you shouldn't compile libnd4j manually, you're using version from maven repository anyway.

**Comment by jiadongzh** [comment]
I am confused. I complied libnd4j  due to the guide at http://deeplearning4j.org/buildinglocally

I just used maven at my local mac osx to compile the java code and find dependencies, and then copy all jar files to the ubuntu server, and run the code by: java -jar helloworld-0.0.1.jar rather than: mvn -f pom.xml exec:java -Dexec.mainClass=...

I don't know whether this process is ok. And how to let maven not using caches?


thanks
jason

**Comment by pwhitey86** [comment]
Also, how do you disable this logging? I used [this](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-cuda-specific-examples/src/main/resources/log4j.properties) log4j properties file, putting it in `src/main/resources` and added the line `log4j.logger.org.reflections=WARN` but I still get similar log messages as in the OP. Thanks!

**Comment by Mi5ke** [comment]
Had the same problem, but eventually realised that deeplearning4j does not use the log4j logging mechanism. It uses a system called logback, which gives very similar-looking output. Logback is controlled by a file called logback.xml - you can find an example in the deeplearning4j examples folders (src/main/resources/logback.xml). Just copy it into your resources folder, or anywhere else on the classpath. Modify the logback.xml to reflect your needs (though logback itself makes various announcements at startup).

Mike

**Comment by raver119** [comment]
Closing this one, since original issue is solved.
