### ISSUE TITLE
MKL dependencies not properly linked?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#261]
I'm building ND4J using one of our internal docker images as a build environment; this has MKL on the path. Build itself is fine.

When building an uber-jar for Spark submit, I find that all of my executor containers are failing with the following:
"Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so."

Extracting the jar file out, it seems that the following dependencies are bundled:
![image](https://cloud.githubusercontent.com/assets/2360237/17658710/edc1bd6e-6310-11e6-9634-25c673668add.png)

Notably those two dependencies (that are failing) aren't included.

Edit: This is an AWS EMR spark cluster of c3.2xlarge instances.

**Comment by treo** [comment]
That looks like the machine it is going to run on doesn't have AVX, and the fallback lib (libmkl_def) isn't around. I wonder what mc3 stands for...

**Comment by saudet** [comment]
@AlexDBlack I've made the modifications necessary to have it bundle those two files as well!

@treo It's apparently for CPUs that support only SSE: https://software.intel.com/en-us/node/528488
