### ISSUE TITLE
Build problems with ICC

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#280]
While trying to build libnd4j using ICC, it crashes. This issue is simply to track the progress on that problem.

As ICC doesn't like all of our constructs, the very simple changes needed to at least start the compilation were made on the icc_compilation branch (see 83a296fe8b3d2fa98d01b586a88723f807e59545).

https://gist.github.com/treo/d0b7610f9072f18449b600a0d585dad4 has the full error log.
https://gist.github.com/treo/e825ba75c5f355ab7abb2d0c38be6fe8 has the log when trying to build with just the bare minimum of flags.

**Comment by agibsonccc** [comment]
https://software.intel.com/en-us/forums/intel-c-compiler/topic/684608

Bug in their compiler. Watch this issue.
