### ISSUE TITLE
Xeon Phi (KNL) Performance

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#281]
I've ran some benchmarks on the Xeon Phi (Knights Landing) and it is a bit underwhelming.
https://gist.github.com/treo/56c7e26683b387dfc6dee04be4451892 shows how it performs.

**Comment by raver119** [comment]
To be investigated: ops parallelism on cpu with higher number of threads.

**Comment by treo** [comment]
I've ran the LenetMnistExample now on my Desktop and in several different configurations on the Phi. As thi

On my desktop (running 0.5.0 release): 6m39s
On the Phi using 64 OpenMP Threads: 8m47s

@raver119 then suggested to run it with ParallelWrapper to see how data parallelism plays into this, which resulted in the following (using #WorkerThreads x #OpenMP Threads Notation)
4x16: 11m05s (F1 at about 98.5%)
64x4: 4m03s (but learning results suffered A LOT, F1 at about 10%)
16x4: 6m56s (learning results still suffered, F1 at about 96%)
16x16: 5m50s (F1 at about 96%)

**Comment by treo** [comment]
With some different compile time options and using libsvml and some more compiler flags:
`-Wall -O3 -std=c++11 -fassociative-math -funsafe-math-optimizations -march=native -mveclibabi=svml -L/opt/intel/compilers_and_libraries/linux/lib/intel64/ -Wl,--no-as-needed -lsvml -lirc -limf -Wl,--as-needed -ffast-math -ftree-vectorize -fvect-cost-model=unlimited -mtune=intel`

With ParallelWrapper:
16x16: 3m08 (F1 at 85%)
4x16: 4m21s (F1 at 97.8 %)
4x64: 6m06s (F1 at 97.9%)

Without ParallelWrapper (F1 at 98.2%):
1x64: 8m48s (CPU utilization seldom going over 2500%) 
1x256: 7m45s (CPU pretty much all the time at 6400%)
1x256: 6m34s (using 8GB of HBM, CPU on average at 3200%; -XX:+UseConcMarkSweepGC)
1x256: 6m29s (using 8GB of HBM, CPU on average at 4800%; -XX:+UseParallelGC)

So the times aren't really that much better, but the CPU utilization seems to stay lower.

**Comment by treo** [comment]
Using ICC (F1 at 98.3%), without any special compiler flags:

1x64: 6m12s (CPU ~3200%)
1x256: 5m58 (CPU ~6000%)

With ParallelWrapper:
4x64: 4m21s (F1 at 92.86%, CPU ~12800%)

I've tried some other things, but can't get CPU Usage to more then 12800% on average.

**Comment by treo** [comment]
Closing this in order to keep further discussion in the new issue by @raver119. #302
