### ISSUE TITLE
On calling `Transforms.cosineSim` 1634 times: [ERROR] Unknown opNum=2 on /Users/saudet/projects/skymind/libnd4j/include/reduce.h:412

### ISSUE THREAD

**Issue by hamid914** [deeplearning4j/libnd4j#330]
I am developing an algorithm using deeplearning4j (based on `ParagraphVectorsInferenceExample.java` on OS X 10.11.6) that needs calculating cosine similarity of a bunch of vectors. This is a piece of code that causes the error:
```
for (int i = 0; i < vector1.size(); i++) {
    for (int j = 0; j < vector2.size(); j++) {
        Transforms.cosineSim(vector1.get(i), vector2.get(j));
    }
}
```
When I limit invocation of `Transforms.cosineSim` to a constant number (1633 on my computer!) there will be no errors at all. But if the limit is increased by one (1634!), this error will be shown at the end of the program for each additional invocation:
`[ERROR] Unknown opNum=2 on /Users/saudet/projects/skymind/libnd4j/include/reduce.h:412`
But in both cases, the program finishes with successful exit code:
`Process finished with exit code 0`
How can I fix this error?
And why this absolute address (/Users/saudet/projects/skymind/libnd4j/include/reduce.h) is given in released library?

**Comment by raver119** [comment]
What ND4j version you're using?

**Comment by raver119** [comment]
Show me your code as gist, it's something else causing your issue, not a cosineSim - it's not a part of reduce function, it's reduce3.

**Comment by hamid914** [comment]
I am using `ND4J-0.6.0` defined in [this](https://github.com/deeplearning4j/dl4j-examples/blob/master/pom.xml#L17) line:
`<nd4j.version>0.6.0</nd4j.version>`

`testCosine()` produces the same output for me: Result: 1.0000001192092896

Sure, I will make a Gist and update this issue.

**Comment by raver119** [comment]
No need. 

Issue is caused by absent Y operand probably. vector2.get(j) returned null i guess.

**Comment by raver119** [comment]
This issue is closed, because that's not libnd4j bug.

If you'll have other issues around that stuff - feel free to open issue at dl4j or nd4j tracker.
