### ISSUE TITLE
JVM Crashes in libnd4j.dll (CPU)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#34]
Trying to train an RNN, and the JVM crashed, see the attached crash log.
[hs_err_pid8820.log.txt](https://github.com/deeplearning4j/libnd4j/files/177843/hs_err_pid8820.log.txt)

**Comment by agibsonccc** [comment]
Is this still happening with the new commits?

**Comment by agibsonccc** [comment]
Fixed with recent commits.
