### ISSUE TITLE
SIGSEGV on im2col

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/libnd4j#345]
Using im2col directly for some image processing. I got this fatal error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001161e03c0, pid=4475, tid=7171
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x4c3c0]  simdOps::Im2col<float>::execSpecial(float*, int*, float*, int*, float*, int*, int*) (._omp_fn.804)+0x5c0
```

I'm essentially using it like this:
```
pyramid[i-1] = Convolution.im2col(src, window[0]*i, window[1]*i, stride[0]*i, stride[1]*i, 0, 0, samePaddingMode);
```

**Comment by raver119** [comment]
The only way to get segfault there is wrong parameters used.

**Comment by crockpotveggies** [comment]
It's happening randomly and not consistently with the same image each time. Perhaps there's a memory reference not properly being released?

**Comment by raver119** [comment]
Not really, you don't know what lies around your referenced memory chunk. 

Could you please try CUDA backend? It's way more sensitive to cross-boundaries accesses, so it should be 99% reproducible there

**Comment by crockpotveggies** [comment]
Here's a Gist of the code. I don't have a GPU to test :(

When loops is `100` then I see the SIGSEGV, but if I lower it to `5` or `10` it disappears.

https://gist.github.com/crockpotveggies/94d992bcffe97c251131c93ed1d3bc99

**Comment by raver119** [comment]
Should've been fixed year ago.
