### ISSUE TITLE
java.lang.RuntimeException: No CUDA devices were found in system

### ISSUE THREAD

**Issue by Anon10W1z** [deeplearning4j/libnd4j#350]
I am having a "no CUDA devices were found in system" error when running the following code:

`System.out.println(CudaEnvironment.getInstance().getConfiguration().getAvailableDevices().size());`

The relevant portion of my build.gradle is as follows:

```
configurations {
    embed
    compile.extendsFrom(embed)
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}

dependencies {
    embed 'org.deeplearning4j:deeplearning4j-core:0.6.0'
    compile 'org.nd4j:nd4j-native-platform:0.6.0'
    compile 'org.nd4j:nd4j-cuda-7.5-platform:0.6.0'
}

jar {
    from configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
}
```

I have tried adding -Djava.library.path="" to my JVM arguments to no avail. I've also tested the CUDA installation using the Nvidia utilities and it shows up fine there.

**Comment by agibsonccc** [comment]
Get rid of nd4j-native and upgrade to 0.7.1 if you can (use 1 backend at a time at least till our next release). Beyond that make sure something simple like device query from the nvidia sdk works. Your problems are not specific to dl4j beyond this so I'm closing this.
