### ISSUE TITLE
Native version of tanh rational approximation

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/libnd4j#351]
As per a discussion with @eraly having an implementation of the rational approximation of the `tanh` activation function can, in certain cases, provide a tremendous speedup.

![screen shot 2017-01-03 at 10 30 41 am](https://cloud.githubusercontent.com/assets/1445295/21618439/bf21378e-d19f-11e6-8d96-e0687a360952.png)

Reference paper: 
[Compact CNN.pdf](https://github.com/deeplearning4j/libnd4j/files/682960/RCNN.Compact.CNN.pdf)

**Comment by AlexDBlack** [comment]
Derivative:

Let a = (1+|y| + y^2 + 1.41645y^4)

then derivative is given by:
(1+sgn(y)(2y + 4*1.41645y^3) / a^2

```java
    private static final double C = 1.41645;

    public static void main(String[] args){

        double eps = 1e-6;
        double step = 0.01;

        for( double d = -2; d<=2; d+= step){
            double empirical = (tanhApprox(d+eps)-tanhApprox(d-eps)) / (2*eps);
            double analytic = tanhDeriv(d);

            double relError = Math.abs(empirical-analytic) / (Math.abs(empirical) + Math.abs(analytic));
            System.out.println(d + "\t" + empirical + "\t" + analytic + "\t" + relError);
        }

    }

    public static double tanhApprox(double y){
        return Math.signum(y) * (1.0 - 1.0/(1+Math.abs(y) + y*y + C * Math.pow(y,4.0)));
    }

    public static double tanhDeriv(double y){
        double a = 1 + Math.abs(y) + y*y + C * Math.pow(y,4);
        return (1 + Math.signum(y) * (2*y + 4*C*Math.pow(y,3))) / (a * a);
    }
```

**Comment by raver119** [comment]
Implemented/merged: https://github.com/deeplearning4j/nd4j/pull/1568
