### ISSUE TITLE
No instructions regarding building libnd4j with CPU (without CUDA)

### ISSUE THREAD

**Issue by euler16** [deeplearning4j/libnd4j#359]

**Comment by tomthetrainer** [comment]
I thought this was more or less covered and that build libnd4j is more or less, 
git clone libnd4j
cd libnd4j
./buildnativeoperations.sh

**Comment by tomthetrainer** [comment]
Adding saudet, and raver119. 

Can you take a look at the 
https://deeplearning4j.org/buildinglocally page and verify that our libnd4j build instructions are accurate?

**Comment by euler16** [comment]
I was referring to the README of this repository

**Comment by raver119** [comment]
I clearly see "Building Manually" section which covers CPU compilation without CUDA, and has instructions for CUDA.

> The GPU-specific instructions below have been commented out, but should be substituted for the CPU-specific commands when building for a GPU backend.

**Comment by raver119** [comment]
As for README: 

> If you don't want the cuda backend, e.g. because you didn't or can't build it, you can skip it:
> mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-cuda-7.5-platform,!org.nd4j:nd4j-tests'

Not sure, what exactly you're missing here.
