### ISSUE TITLE
Build error for libnd4j

### ISSUE THREAD

**Issue by rcorbish** [deeplearning4j/libnd4j#368]
I receive an error building libnd4j - clean pull from github

https://pastebin.com/SAkFVcme

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

Linux 4.10.0-14-generic #16-Ubuntu SMP

**Comment by raver119** [comment]
gcc 5.4, not reproducible. However, issue is logical: namespace conflict...

**Comment by saudet** [comment]
Has this been fixed?

**Comment by rcorbish** [comment]
In gcc5.4 there is not a problem. I checked, that is the compiler indicated on the build - so this is fixed. I was using 6.3

**Comment by huitseeker** [comment]
@rcorbish It would be good to have your gcc exact `--version` for future reference. Also, have you tried `TRICK_NVCC=YES` as indicated here? This is mandatory on gcc 6.

**Comment by rcorbish** [comment]
I did try that. For now I put a docker image to build using the 5.4 compiler

**Comment by raver119** [comment]
I wasn't able to use gcc6 for cuda as well, so i've just installed gcc-5 and using it. CUDA 9 will support gcc6 afaik.
