### ISSUE TITLE
CUDA build issue - Windows

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#395]
CUDA build is failing for me on Windows:
https://gist.github.com/AlexDBlack/bf68a324750df4ad5c0a9ecaf5587dd8

Note that the CPU build (```buildnativeoperations.sh```) compiles successfully.

**Comment by saudet** [comment]
`uint64_t` -> Visual Studio didn't provide a definition for those until 2015. We should be using `long long`.

**Comment by saudet** [comment]
Actually, we could just use `Nd4jIndex` like everywhere else. Any reason not to @raver119 ?

**Comment by raver119** [comment]
Hold on, that uint64_t stuff was there since 0.6.0. Something else caused this issue...

**Comment by raver119** [comment]
Yep, something in your TRICK_NVCC commit causes that. I've defined uint64_t to long long etc, but compilation still fails, just in VC includes this time. One merge before - everything compiles fine "as is"

**Comment by raver119** [comment]
```
C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/../../../VC/INCLUDE\stdint.h(15): error: invalid combination of type specifiers

C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/../../../VC/INCLUDE\stdint.h(15): error: invalid combination of type specifiers
```

**Comment by raver119** [comment]
Funny. It's caused literally by removed `#include <mutex>`, once i add that back - everything compiles fine again

**Comment by raver119** [comment]
I've temporary added back that include, for MSVC only, but i still wonder - how it affects compilation...

**Comment by saudet** [comment]
Well, we shouldn't rely on including `mutex.h` just to define `uint64_t`. What about we switch that to `Nd4jIndex` like everything else?

**Comment by raver119** [comment]
I've said few posts above, even if i define uint64_t, another problem arises:

```
C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/../../../VC/INCLUDE\stdint.h(15): error: invalid combination of type specifiers

C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/../../../VC/INCLUDE\stdint.h(15): error: invalid combination of type specifiers
```

And i'm not quite sure what's up with it...

**Comment by raver119** [comment]
Ah lol ye, that's just conflicting redefinition, unisgned long long should be used

**Comment by lukeczapla** [comment]
I have a similar problem on mac (exact same error `invalid combination of type specifiers`) so I put back that `#include <mutex>` and it's at least going forward with compilation, but it's taking forever.... I think there needs to be custom flags for clang. maybe it's caught in an infinite loop because it's not outputting the correct files.

**Comment by raver119** [comment]
Original issue has nothing to do with macOS. Closing it now.
