### ISSUE TITLE
Build failure for ios-armv7

### ISSUE THREAD

**Issue by ibinti** [deeplearning4j/libnd4j#398]
```
./buildnativeoperations.sh -o ios-armv7
```
will cause 
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    clang-omp

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    clang-omp

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```
This is due to two lines in `cmake/ios-armv7.cmake`
```
set(CMAKE_C_COMPILER   "clang-omp")
set(CMAKE_CXX_COMPILER "clang-omp")
```

There is a known relevant issue #300, where `clang-omp` is no longer available from `brew install clang-omp`.

**Comment by ibinti** [comment]
It seems one needs to use `llvm` for this job. Please pardon my ignorance, but isn't `clang` a front-end for `llvm`? I was believing using `clang` is same as using `llvm`.

**Comment by ibinti** [comment]
If I use just `clang` instead of `clang-omp`, build stops with a fatal error:
```
/libnd4j/include/helpers/helper_random.h:19:10: fatal error: 'mutex' file not found
#include <mutex>
```

**Comment by agibsonccc** [comment]
We normally use gcc on mac. Is there a problem with that for ios?

**Comment by ibinti** [comment]
I have no real knowledge on that. But a little bit of Googling tells me that there is a binary compatibility issues between clang and gcc. Based on that reason, now this is my wild guess why gcc is not for iOS. So it means objects may not be linked together well if one is compiled with clang and the other is with gcc. This is a problem on iOS, where Apple enforces static linking for the app. Everything must be linked together into a monolith one binary. No shared or dynamic libraries are allowed on iOS. Xcode and all iOS frameworks are believed to work with clang. Probably gcc will have a hard time to link with the iOS frameworks. On the other hand, one can use dynamic libraries, like libnd4jcpu.dylib on macOS, without an issue.

**Comment by ibinti** [comment]
Trying different clangs.

Xcode 8.3.3: does not recognize `-fopenmp`, and stops at  `mutex` not found
```
clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
```

Xcode 9.0: does not recognize `-fopenmp`, and stops at  `mutex` not found
```
clang --version
Apple LLVM version 9.0.0 (clang-900.0.22.8)
Target: x86_64-apple-darwin16.6.0
```
LLVM 4.0: does recognize `-fopenmp`, but stops at  `mutex` not found
```
clang --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.6.0
```

**Comment by agibsonccc** [comment]
Hmm - the reason I'm asking is because our mac builds use gcc and no one has complained. Clang doesn't have openmp, they broke it on mac. That's wh you're seeing these problems.

**Comment by ibinti** [comment]
I am looking into why `mutex` is needed in the first place, and if there is any workaround.

**Comment by ibinti** [comment]
Adding `-stdlib=libc++`, then LLVM 4.0 did compile and generated `libnd4jcpu.a`
For Xcode clangs, remove `-fopenmp ` and add `-stdlib=libc++` , compiled and linked to `libnd4jcpu.a`

So it does build with `-stdlib=libc++`.
