### ISSUE TITLE
Build issue on android-x86

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/libnd4j#407]
Everything builds find on android-arm, but the old GCC compiler doesn't seem to be able to compile for android-x86:
```
/mnt/OS/projects/skymind/libnd4j/blas/cpu/NativeOps.cpp: In function 'static T simdOps::EqualsWithEps<T>::postProcess(T, Nd4jIndex, T*) [with T = float16]':
/mnt/OS/projects/skymind/libnd4j/blas/cpu/NativeOps.cpp:2969:1: internal compiler error: in make_ssa_name_fn, at tree-ssanames.c:136
```

I've narrowed it down to the new `NativeOps::execReduce3AllHalf`. If we comment out the call to `execReduce3All()` then it builds. Further, it is not limited to `EqualsWithEps`. It trips on whichever op is last in REDUCE3_OPS.

Removing all optimization flags doesn't help, so it's not related to optimization, but it is related to x86 and float16.

**Comment by raver119** [comment]
OMFG...

**Comment by raver119** [comment]
Which GCC version is that?

**Comment by saudet** [comment]
GCC 4.9, but for Android, and now deprecated by Google

**Comment by raver119** [comment]
Interesting. We already have few FP16 ops on CPU for quite a while. Why this one is different...

**Comment by raver119** [comment]
Fixed long ago.
