### ISSUE TITLE
CUDA build issue on mac

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/libnd4j#409]
Hi guys, this is not a big deal, but it was suggested that I post an !issue about it on gitter.  On CUDA 8.0 it expects to use clang and clang++ on Mac and seems to run it automatically within its binary, but some of the flags passed to the compiler throw errors, `-fopenmp` I believe is one such example, they are gcc specific but CUDA 8.0 won't allow usage of gcc (I used gcc 5.2 to compile everything else with no problems and have a fully operational build for native platform).  

I tried setting a number of environment variables like CXX and CC and editing the `buildnativeoperations.sh` information but that will not override the nvcc settings.  This looks like it effects both libnd4j and nd4j.   I tried to use TRICK_NVCC=YES but it did not make it use gcc 5, even though everything else was using it.

I was pointed to this commit but it does not work: https://github.com/deeplearning4j/libnd4j/commit/6654b3604440540bb10421aebc447061ff6d155b

It looks like nvcc directly invokes clang so the only thing I tried was commenting out the `-fopenmp` setup part of the cmake file, but it compiled a long time before finally giving these errors:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config(259): error: invalid combination of type specifiers
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config(260): error: invalid combination of type specifiers`

(those seem to be temporary files created during the compilation process so I don't know what they said)

**Comment by saudet** [comment]
Are you sure you're not trying to use Xcode 8 on Mac OS X 10.11? It's not supported by CUDA:
http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#system-requirements

**Comment by lukeczapla** [comment]
well, I got it to keep compiling by putting back this `#include <mutex>` statement from another thread, but yes I am using 10.11 and Xcode.  Let me see if I can revert back to Xcode 7

**Comment by lukeczapla** [comment]
I'm trying again with 7.0.3 since it's supported.  I had to put back `#include <mutex>`  to get rid of the errors

**Comment by saudet** [comment]
Strange, we're not using anything from that header file. Anyway, it's not supported by GCC 6, but if that's what Clang needs in some circumstances, we could put it back just for Mac if you'd like. Please send a pull request.

**Comment by lukeczapla** [comment]
Ok, I was successful!  So the main issue were these lines in the CMakeLists.txt (I had to comment them out) and it was OK to build the whole thing with clang LLVM 7.0.3 for CUDA:

`
        #find_package(OpenMP)
        #if (OPENMP_FOUND)
        #    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
        #    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        #endif()
`

**Comment by lukeczapla** [comment]
so with the TRICK_NVCC patch maybe that could be integrated into the procedure to "trick" nvcc, meaning nvcc is always going to use clang on Mac but it will work without those options like -fopenmp

**Comment by saudet** [comment]
We don't need to trick anything. OpenMP shouldn't be used with Clang at all.

**Comment by lukeczapla** [comment]
yea I think that it will compile fine on clang, but I'll pull a fresh copy and try it just to check

**Comment by lukeczapla** [comment]
CLOSED.  It's fine now.  The thread on the similar problem on Windows is probably ok now too.
