### ISSUE TITLE
b40c doesn't build on Mac

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/libnd4j#419]
Build log:
http://master-jenkins.skymind.io:8080/job/dl4j/job/all-multiplatform/1628/console

Mac OS X 10.12.3, Apple LLVM version 8.0.0 (clang-800.0.42.1), CUDA Version 8.0.62

Does it work for you @raver119 ?

**Comment by raver119** [comment]
My mac doesn't have CUDA-capable gpu, so i don't know :(
Let me exclude it for macos.

**Comment by saudet** [comment]
It's not running any tests, it just doesn't seem to build. Does it build on your Mac?

**Comment by raver119** [comment]
I have no CUDA toolkit on mac, since it has no CUDA gpu - i've never tried to install toolkit. 
I'll just exclude it today, i have open branch in libnd4j that should get into release, so i'll exclude it right here once i finish with long tads

**Comment by raver119** [comment]
Please confirm it works now.

If not - tell me, and i'll just get rid of this radix impl :(

**Comment by saudet** [comment]
It builds! Thank you
