### ISSUE TITLE
Softmax derivative implementation incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#440]
See math below. 

Looks like we only implement one part of this: i.e., output * (1 - output), for the diagonal.
https://github.com/deeplearning4j/libnd4j/blob/4942662b4693746cfce990bf38d2ed00d7786351/include/ops/special_ops.h#L1798
We are missing the sum and i != j case.

![image](https://user-images.githubusercontent.com/2360237/29654273-e855f45c-88ef-11e7-9b0e-c4a70fcd6764.png)
![image](https://user-images.githubusercontent.com/2360237/29654285-f75915b0-88ef-11e7-8c9a-37b988489c5e.png)
![image](https://user-images.githubusercontent.com/2360237/29654288-f9efb072-88ef-11e7-8a9d-63479632859f.png)

**Comment by raver119** [comment]
Got test?

**Comment by AlexDBlack** [comment]
New test added on Adam's branch (Nd4jTestsC) here: https://github.com/deeplearning4j/nd4j/pull/2063/files

**Comment by raver119** [comment]
Should have been fixed, now this op is custom op.
