### ISSUE TITLE
Element wise max/average given a list of INDArrays

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#444]
In order to support https://github.com/deeplearning4j/deeplearning4j/issues/3915

We need to be able to take as input a list of ndarrays of the same size and return an ndarray of that same size where each element is the max (or average) of the corresponding elements

For example:
```
A = [1,0,0,0,0]
B = [0,2,0,0,0]
C = [0,0,3,0,0]
D = [0,0,0,4,0]
E = [0,0,0,0,5]

mergeMax(A,B,C,D,E) = [1,2,3,4,5]
mergeAvg(A,B,C,D,E) = [0.2,0.4,0.6.0.8,1.0]
```

**Comment by raver119** [comment]
Implemented, will be merged tomorrow.

**Comment by maxpumperla** [comment]
@raver119 took you 33 mins to do that? dope!

**Comment by raver119** [comment]
Ye, it's hard to shine at 2300.. :/
