### ISSUE TITLE
Backprop for "Element wise max/average given a list of INDArrays"

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#445]
This is the second part for the backward pass through the merge operations here
https://github.com/deeplearning4j/libnd4j/issues/444

The backward pass through the merge average can be handled easily. 

But we will need a new operation that will handle the backward pass through the merge max. 

It will have to return the same shape array as the ones in the list. Each element in the array will be the index of the max element.

From the example in the issue filed before:
```
A = [1,0,0,0,0]
B = [0,2,0,0,0]
C = [0,0,3,0,0]
D = [0,0,0,4,0]
E = [0,0,0,0,5]

mergeMax(A,B,C,D,E) = [1,2,3,4,5]

We also need something like
mergeMaxIndex(A,B,C,D,E) = [0,1,2,3,4] //each elements will always be [0,n-1] where n is the size of the list

```

cc: @AlexDBlack @raver119 Are we polluting the codebase by adding ops like this? Should we just for same diff? I would prefer to just get this one done and close out the merge vertex issue Max filed. But raising the concern just in case.

**Comment by eraly** [comment]
Raver's test showing usage

https://github.com/deeplearning4j/nd4j/blob/29bcb3a93e48f9dde85b63bf0741659c38ce3830/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/custom/CustomOpsTests.java#L168

**Comment by raver119** [comment]
I don't see any concerns here. We need it? We'll have it.

**Comment by raver119** [comment]
p.s. will add shortly.

**Comment by raver119** [comment]
Implemented and merged. Feel free to close issue once you're happy.
