### ISSUE TITLE
CUDA build with GCC 6 broken

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/libnd4j#450]
CUDA doesn't support GCC 6 with C++11, this change breaks GCC 6:
https://github.com/deeplearning4j/libnd4j/commit/b450a333a9898cbbad757305a69c6442498a986d#diff-f88dea0ef3ab99bb0dad2f4aad7dcd76L69
Do we need C++11 and thus require GCC 5 for builds now?

**Comment by raver119** [comment]
Which CUDA version doesn't support c++11? 7.5 i guess?

**Comment by saudet** [comment]
No, CUDA 8, but only with GCC 6 (or 7). Anyway, CUDA 9 supports GCC 6 (and maybe 7), so we should start thinking of dropping CUDA 7.5 and move to builds for CUDA 8 and 9 only, I guess? @agibsonccc ?

**Comment by agibsonccc** [comment]
I would be ok switching to cuda 9 now.

**Comment by raver119** [comment]
Ok, i'll revert it back, once i finish with 4.9 check

**Comment by raver119** [comment]
Reverted back to c++98, should compile fine now.

**Comment by raver119** [comment]
I guess this one can be closed now. CUDA migration completed, gcc 6 works fine.
