### ISSUE TITLE
CPU Backend Crashes JVM on MLPMnistSingleLayerExample (Windows)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#49]
Using the current master, the cpu backend crashes the JVM when running MLPMnistSingleLayerExample.

[hs_err_pid1312.log.txt](https://github.com/deeplearning4j/libnd4j/files/182067/hs_err_pid1312.log.txt)

**Comment by treo** [comment]
It looks like this problem is caused by this commit https://github.com/deeplearning4j/nd4j/commit/3a3b9166b93af1768d3a3831dbc2b0e7f955caea

**Comment by treo** [comment]
```java
package com.example;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class App 
{
    public static void main( String[] args ){
        INDArray indArray = Nd4j.create(1);
        indArray.assign(Nd4j.ones(1));
    }
}
```

This minimal example crashes for me.

**Comment by AlexDBlack** [comment]
For what it's worth: no issue for me on Windows 8.1, on either MLPMnistSingleLayerExample or the above minimal example...

**Comment by treo** [comment]
I should also add that it works on my linux vm, but on windows 10 it simply crashes.

**Comment by treo** [comment]
Looks like it was something weird with intellij, restarting it resolved the issue.
