### ISSUE TITLE
Clang support 

### ISSUE THREAD

**Issue by viviantitus** [deeplearning4j/libnd4j#502]
Easy integration with Cocoa and native Obj-C libs on macOS and iOS

**Comment by saudet** [comment]
We can already build with Clang, it will just not work with OpenMP at the moment, see https://github.com/deeplearning4j/libnd4j/pull/383, for example. Is this what you are looking for?

**Comment by viviantitus** [comment]
Certain typos in your code is not supported in clang. I am intergrating accelerate. This is repo link: https://github.com/viviantitus/libnd4j-accelerate

**Comment by raver119** [comment]
Yes, there's definitely some issues possible with new graph-related stuff - we're using gcc and msvc to ensure stuff compilation, and tests are being run with gcc only for now.

**Comment by raver119** [comment]
AFAIK clang is definitely supported now, and IS used within tests toolchain.
