### ISSUE TITLE
CUDA separable compilation

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/libnd4j#509]
Recently @shyrma and me added parallel compilation for CPU, and basic parallel compilation for CUDA.

But, CUDA will need more love to meet comfortable compilation/recompilation time levels, before we start adding CUDA support for Graph. 10 minutes per compilation attempt doesn't sound any viable for  rapid development.

So, we should take a look into available options which could give us separable compilation AND further compilation time decrease.

**Comment by saudet** [comment]
If we can have 10 or more compilation units, not removing the whole build directory on each build would help `make` just rebuild files that have actually changed (incremental build). Rebuilds would be less than 1 minute in that case.

**Comment by raver119** [comment]
Yes, during tests we already use incremental builds a lot. But CUDA is slightly different story. We have some serious overlaps there... And there's few blocks that take most of compilation time. We should either redesign those completely, or, somehow break device code isolation, to provide reuse of kernels between different compilation modules. Like CPU c++ works.

**Comment by agibsonccc** [comment]
Can't we close this now?

**Comment by raver119** [comment]
No, it’s still TODO

пн, 16 окт. 2017 г. в 10:27, Adam Gibson <notifications@github.com>:

**Comment by raver119** [comment]
Implemented & merged.
