### ISSUE TITLE
Compilation errors with shape definition headers

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#517]
https://gist.github.com/agibsonccc/bd89319517f981101bc55be7d2109ff4

**Comment by saudet** [comment]
This fixes it on Linux, at least:
https://github.com/deeplearning4j/libnd4j/tree/sa_buildfix
Testing on Windows...

**Comment by raver119** [comment]
What's the OS and compiler version? I've checked macOS and Linux less than  12 hours ago.
