### ISSUE TITLE
Allocating big (ones) array crashes Display Driver (CUDA, Windows)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#53]
When running the following my display driver crashes. I'm running the current state of jita_2_banana_taste, so @raver119 that may interest you as soon as you have your windows setup running.

```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {
    public static void main(String... args){
        // Usually Works
        //Nd4j.ones(1024 * 1024 * 11);
        // Sometimes Works, sometimes crashes the display driver without an error message in output
        //Nd4j.ones(1024 * 1024 * 12);
        // Always crashes display driver
        Nd4j.ones(1024 * 1024 * 13);
    }
}
```

Output for the crashing case is:
```
o.n.j.c.CudaEnvironment - Devices found: 1
o.n.j.c.CudaEnvironment - Device [0]: Free: 3509226700 Total memory: 4294967296
o.n.j.h.i.CudaZeroHandler - Mapping device [0] to thread [1]
o.n.j.a.i.AtomicAllocator - Starting device GC for device: 0
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 1
CUDA error at C:/Users/dubs/Documents/stuff/clean/master/libnd4j/blas/cuda/NativeOps.cu:1767 code=4(cudaErrorLaunchFailure) "cudaStreamSynchronize(*stream)" 
```

Sometimes the crashes seem to be so severe that my computer simply reboots.

**Comment by raver119** [comment]
No worries, that's "working as intended". Allocation boundaries are disabled in banana branch for memleaks testing. It won't get to master without boundaries checks :)

**Comment by raver119** [comment]
Stop, that's not boundaries, that's just 13m elements.

**Comment by raver119** [comment]
Maybe you have a typo, and that's 13B elements?

**Comment by treo** [comment]
I'm running the example exactly like that. So yes, I am sure that it's just 13m elements.

**Comment by raver119** [comment]
Please confirm that Nd4j.create(1024 * 1024 * 13) doesn't fails on your system, and i'll assume that's kernel failure, not memory ne.

**Comment by treo** [comment]
> Please confirm that Nd4j.create(1024 * 1024 * 13) doesn't fails on your system

The create variant does not fail. Even running `.sumNumber()` on it does work.

**Comment by raver119** [comment]
Great thanks!

**Comment by raver119** [comment]
@treo i've checked original issue: kernel launch params look safe: that's only 17k blocks per grid. A bit bigger then 0.

And  on current libnd4j master works fine for me.

**Comment by treo** [comment]
Just tried it again on current master, and it still crashes the Display driver (and on a re-try even crashed the whole system).

**Comment by treo** [comment]
This is related to https://github.com/deeplearning4j/nd4j/issues/755, and disabling tdr did help.
