### ISSUE TITLE
 tf.nn.bias_add and add

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#548]
If a user were to write a NN with the low level tf api they could use tf.add or just the + for the bias operation instead of bias_add. In tensorflow this gets turned into a broadcast add. This gets mapped to a pairwise transform currently and we should consider doing the auto broadcast to avoid error on import.

**Comment by raver119** [comment]
Ye. We should provide transparent auto broadcast for all basic math operations.

**Comment by raver119** [comment]
cc @shyrma

**Comment by raver119** [comment]
Hypothetically implemented. On libnd4j side at least.
