### ISSUE TITLE
required CMake version should be 3.8

### ISSUE THREAD

**Issue by johanvos** [deeplearning4j/libnd4j#557]
The documentation at https://github.com/deeplearning4j/libnd4j mentions that in order to build libnd4j one of the prerequisites is CMake 3.2

But CMakeLists.txt has a minimal required version at 3.8:
`cmake_minimum_required(VERSION 3.8)`

**Comment by raver119** [comment]
It's even worse. It'll be 3.9 soon. But yea, we should update documentation

**Comment by tomthetrainer** [comment]
I made the change to Readme here. 

https://github.com/deeplearning4j/libnd4j

Stated current is 3.8 as of Nov 2017, in near future will be 3.9

I am closing this on the assumption that the README was the only document with the old information. 

Re-open issue if there are other docs with this error.
