### ISSUE TITLE
biasadd 

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#559]
It was working. Not sure what happened. It's not anymore. After the op all outputs are zero. 

Simple test is checked in under "bias_add". Branch name is eralyTF in nd4j and I use libnd4j master

Uncomment modelName to bias_add in line below:

https://github.com/deeplearning4j/nd4j/blob/daedc2176cb29342c1acf37114d7187640800694/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphTestSingle.java#L28

Python code is:

```
in_0 = tf.placeholder("float", [None, 4], name="input")
biases = tf.Variable(tf.lin_space(1.0, 4.0, 4), name="bias")
output = tf.nn.bias_add(in_0, biases, name="output")

init = tf.global_variables_initializer()
all_saver = tf.train.Saver()
with tf.Session() as sess:
    input_0 = np.linspace(1, 40, 40).reshape(10, 4)
    sess.run(init)
    prediction = sess.run(output, feed_dict={in_0: input_0})
```

**Comment by raver119** [comment]
Hypothetically biasadd was fixed today. Please confirm/decline.

**Comment by eraly** [comment]
Looks good. Thanks.
