### ISSUE TITLE
CUDA build broken on Windows

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#560]
CPU build is fine, but CUDA fails with:
https://gist.github.com/AlexDBlack/08907ff5b3f0d6bc7b404d3b8fbca922

**Comment by raver119** [comment]
Fixed

**Comment by AlexDBlack** [comment]
Reopening - due to a different issue this time.
Linux build is fine, just the windows build again.
https://gist.github.com/AlexDBlack/c5a67de6dcbefd0d5cf418085f9e3e1d

**Comment by raver119** [comment]
Fixed again.

**Comment by AlexDBlack** [comment]
Broken again :(

https://gist.github.com/AlexDBlack/5fcdf863cf09f66dc576af75fa1588fb

**Comment by raver119** [comment]
Fixed again.
