### ISSUE TITLE
Missing  a Gather like op

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#566]
From onnx: 

 
Given DATA tensor of rank r >= 1, and INDICES tensor of rank q, gather
  entries of the outer-most dimension of DATA indexed by INDICES, and concatenate
  them in an output tensor of rank q + (r - 1).

  Example:
    DATA  = [
        [1.0, 1.2],
        [2.3, 3.4],
        [4.5, 5.7],
    ]
    INDICES = [
        [0, 1],
        [1, 2],
    ]
    OUTPUT = [
        [
            [1.0, 1.2],
            [2.3, 3.4],
        ],
        [
            [2.3, 3.4],
            [4.5, 5.7],
        ],
    ]

**Comment by raver119** [comment]
TL/DR: we have gather_list. Now we need gather. Pretty much the same thing as pullRows, so it should be ported to CustomOps.

**Comment by shyrma** [comment]
Hi guys!
We have implemented and tested this operation.
In general it works pretty much like tensorflow analogue except we don't have 1D arrays.
In this case we use 2D vectors and neglect unity in their shape. For example input array has shape {2,3,4}, axis=1 and indices are stored in vector with shape {1,6}.  Result of gather operation is then:
{2,6,4}  (instead expected {2,1,6,4})
