### ISSUE TITLE
Implement parallel merge for CPU

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#57]
OpenMP is not as clever as expected, so a parallel merge has to be implemented by hand.

Done right, this should solve https://github.com/deeplearning4j/nd4j/issues/733 as a side effect.

There is the ["reduction" pragma](https://msdn.microsoft.com/en-us/library/2etkydkz.aspx) but it needs more explicitness than is possible with the current structure of ops.

**Comment by agibsonccc** [comment]
Pretty sure I did this?
