### ISSUE TITLE
Matmul order

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#574]
Matmul results from TF don't match. Results (as in the elements) is correct but taking the ordering into account it is not correct.

Run TFGraphTestSingle.testOne on eralyTF branch of nd4j with modelName set to "math_mul_order"

<img width="892" alt="screen shot 2017-11-17 at 1 17 37 pm" src="https://user-images.githubusercontent.com/8340500/32969372-bfafb672-cb99-11e7-9688-5eff7f39a4e9.png">

**Comment by shyrma** [comment]
Hi, Susan.
Thank you for your important comment!
Actually this bug was already fixed few days ago (accidentally while optimizing of indexing of array elements )
