### ISSUE TITLE
keeping dimensions while reducing array

### ISSUE THREAD

**Issue by shyrma** [deeplearning4j/libnd4j#585]
Currently we have no option to keep dimensions in reduce operation. However such is present in tensorFlow library. To be more precise, what we have now is:
arr(2x3x4)
arr.reduce(1) -> (2x4)
and we would like to have 
arr.reduce(1, keepDims=true) -> (2x1x4)
as well

**Comment by raver119** [comment]
cc @agibsonccc

**Comment by raver119** [comment]
Implemented.
