### ISSUE TITLE
buildnativeoperations.sh - CUDA_TOOLKIT_DIR not found even if set on enviorment path

### ISSUE THREAD

**Issue by dhaalves** [deeplearning4j/libnd4j#641]
![captura de tela de 2017-12-17 22-39-48](https://user-images.githubusercontent.com/6765855/34087497-944873c6-e38a-11e7-83b4-5779012e7205.png)

workaround:
FindCMake.cmake looks for /usr/local/cuda. In your case, that directory might not be there. Just create a symbolic link of that name to your actual CUDA installation directory:
sudo ln -s /usr/local/cuda-9.0 /usr/local/cuda

**Comment by raver119** [comment]
There's planned migration to CMake 3.8+ in our roadmap for CUDA, so FindCUDA.cmake will finally become obsolete.
