### ISSUE TITLE
Conv3D missing data format logic

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#678]
https://github.com/deeplearning4j/libnd4j/blob/master/include/ops/declarable/generic/convo/conv3d_ops.cpp

See: https://github.com/deeplearning4j/nd4j/blob/029c8edc8d82fcd19cc7c5bc3578de0e2126fcc9/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/resources/ops.proto#L5292

**Comment by raver119** [comment]
At this point it's NCDHW only.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/libnd4j/blob/05b599cfd0aee8003812613f6ce0fe2cf989a2c6/include/ops/declarable/generic/convo/conv3d.cpp#L99
