### ISSUE TITLE
Optimize toFlattened

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#68]
Current performance figures: (milliseconds, 1000 runs)
As of: 6pm Sunday 3rd April (PDT), after merging the bettertoflattened branch

**Size** | **From Order** | **Flatten To Order** | **bettertoflattened**
--- | --- | --- | --- | ---
1000x1000 | c | c | 1463
1000x1000 | c | f | 21907
1000x1000 | f | f | 1972
1000x1000 | f | c | 21024

**Note: Appears to be running on single-core, as far as I can tell**

Test code: https://gist.github.com/AlexDBlack/6da5405b8043e5f8c1c613dab142d6c9

////////////////////////////////

Currently: toFlattened uses ind2sub/ind2subc, one call for each element in the array
https://github.com/deeplearning4j/libnd4j/blob/e080e0a65b03a9801ed36cc025098fccd10c0797/blas/cpu/NativeOps.cpp#L1379

This approach is going to be too slow in practice, and we're seeing this as a bottleneck.

One thing I realized: toFlattened(order) with order is actually the exact same operation as dup(order), in terms of the contents in the buffer. The only difference there is the shape information. Thus we could/should leverage the same code for both.
- so if we do a toFlattened('f'), our resulting row vectors contains the array in an f order traversal of the values
- similarly if we do a dup('f') our buffer contains the values in f order...

here's some other thoughts that might help to optimize this:
- special case: full buffer/"standard strides for the shape"/"is contiguous in memory" arrays: can simply do memory copy if original and flattening orders match
  - flattening a full-buffer f order to f order: buffer already in the order we want
  - ditto for c order to c order
  - this special case should come up a fair bit in practice
- general case, flattening to f order: this is equivalent to doing an f-order traversal of 1d tensors along dimension 0
  - i.e., for a [2,3,2] we are doing tensors along dimension 0 with starting offsets given by [0,0,0], [0,1,0], [0,2,0], [0,0,1], [0,1,1], [0,2,1]
- general case, flattening to c order: this is equivalent to doing a c-order traversal of 1d tensors along the last dimension
  - i.e., for a [2,3,2] we are doing sensors along dimension 2 with starting offsets given by [0,0,0], [0,1,0], [0,2,0], [1,0,0], [1,1,0], [1,2,0]

(though I think technically it might be better/more efficient to do the first dimension with size > 1, and the last dimension with size > 1 for f and c respectively?)

If we use the 1d tensor approach, we end up doing a bunch of copy ops on the buffer (all we need is tensor start offset, tensor length (number of elements), and stride)

**Comment by AlexDBlack** [comment]
bettertoflattened branch: currently getting JVM crashing/loops on the following cases:

```java
    @Test
    public void testToFlattened(){
        INDArray inC1 = Nd4j.create(new int[]{10,100},'c');
        INDArray inC2 = Nd4j.create(new int[]{1,100},'c');

        INDArray inF1 = Nd4j.create(new int[]{10,100},'f');
//        INDArray inF1 = Nd4j.create(new int[]{784,1000},'f');
        INDArray inF2 = Nd4j.create(new int[]{1,100},'f');

        Nd4j.toFlattened('f',inF1); //ok
        Nd4j.toFlattened('f',inF2); //ok

        Nd4j.toFlattened('f',inC1); //crash
        Nd4j.toFlattened('f',inC2); //crash

        Nd4j.toFlattened('c',inF1); //crash on shape [784,1000]. infinite loop on shape [10,100]
        Nd4j.toFlattened('c',inF2); //ok

        Nd4j.toFlattened('c',inC1); //ok
        Nd4j.toFlattened('c',inC2); //ok
    }
```

**Comment by treo** [comment]
I've added your toFlattened benchmark to my JMH based one, but I like using powers of 2 as inputs, so I'm using a Shape of 1024x1024.

These are the results from before the merge:
```
Benchmark                    Mode   Cnt      Score     Error  Units
Nd4j.toFlattened_CC_Small  sample  3123  11609,803 ±   7,962  us/op
Nd4j.toFlattened_CF_Small  sample  1861  19509,673 ± 249,213  us/op
Nd4j.toFlattened_FC_Small  sample  1975  18382,342 ± 208,104  us/op
Nd4j.toFlattened_FF_Small  sample  3002  12063,138 ±  44,201  us/op
```

And this are the numbers after the merge (with the windows fix):

```
Benchmark                    Mode    Cnt      Score     Error  Units
Nd4j.toFlattened_CC_Small  sample  31892   1280,396 ± 229,296  us/op
Nd4j.toFlattened_CF_Small  sample   1867  19443,482 ± 223,347  us/op
Nd4j.toFlattened_FC_Small  sample   1961  18512,500 ± 173,460  us/op
Nd4j.toFlattened_FF_Small  sample  32616   1268,712 ± 223,645  us/op
```

So it looks like the case were the ordering stays the same is a lot better now, while the case where the ordering has to change didn't improve.

And I have to confirm that it appears to be using only a single core.

**Comment by treo** [comment]
To add to this again: The 'slow' case, i.e. where we go from C->F or F->C, is where actually most of the time is spent when training an actual model.

**Comment by agibsonccc** [comment]
@eraly did this already
