### ISSUE TITLE
No pairwise distance implementations?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#706]
As far as I can tell, we don't have a libnd4j implementation for the following pairwise distances:
* EuclideanDistance
* ManhattanDistance
* CosineDistance

**Comment by AlexDBlack** [comment]
Note that we've got forward (and soon - backprop) implemented in the ND4J/SameDiff classes, which can be used as a reference.

**Comment by raver119** [comment]
How comes? That's just reduce3 operation too. Just no axis given.

**Comment by AlexDBlack** [comment]
Ok, I'll close this - I was expecting a non-legacy op, and was confused by the fact that CosineSimilarity/CosineDistance/Jaccard/ (in ND4J) overrides exec() (afaik this is legacy code that just needs to be removed, and isn't actually used).

No native backprop methods, and issues with exec along dimension, but those are separate issues.
