### ISSUE TITLE
Strided slice: only supports subset of tensorflow functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#709]
https://github.com/deeplearning4j/libnd4j/blob/522ea847465777355c86f6a463982affb55b5bbd/include/ops/declarable/generic/parity_ops/strided_slice.cpp#L16-L18

https://www.tensorflow.org/api_docs/python/tf/strided_slice

Notably, we only have the begin/end/stride args.
We do *not* have the following args: begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask

**Comment by AlexDBlack** [comment]
Another observation/case to handle:

https://www.tensorflow.org/api_docs/python/tf/strided_slice
> begin, end, and strides will be all length n. n is in general not the same dimensionality as input.

Our code currently seems to assume that these 3 arrays always have length equal to the rank of the input array:
https://github.com/deeplearning4j/libnd4j/blob/522ea847465777355c86f6a463982affb55b5bbd/include/ops/declarable/generic/parity_ops/strided_slice.cpp#L20-L22

**Comment by raver119** [comment]
No, we do have support for all masks i think.

Also, you're looking into ultra-outdated branch. It's something like draft :)

Check out master please: https://github.com/deeplearning4j/libnd4j/blob/master/include/ops/declarable/generic/parity_ops/strided_slice.cpp

**Comment by AlexDBlack** [comment]
OK, closing this
