### ISSUE TITLE
Add slice (and strided_slice) backprop ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#710]
I can't see an easy way to do this from Java currently...

Consider slice (which is just a bunch of NDArrayIndex.interval(x,y) ops), this returns a copy. (so I can't just do a slice + assign as it's not in-place)

Backprop op is simple:
- output array is equal to the size of the original slice op input
- gradient array is equal to the size of the original (sliced) output

Take the backprop output array, slice it same as the original input, then assign the gradient (and 0s for all other values).

**Comment by AlexDBlack** [comment]
Bump - this is still important, and still isn't possible as far as I can tell. I would consider this a blocker for release.

**Comment by raver119** [comment]
Should be implemented now.
