### ISSUE TITLE
jvm crash

### ISSUE THREAD

**Issue by anzhilin** [deeplearning4j/libnd4j#714]
this is a piece of hs_err.log:
`
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007ff55834cb90, pid=11330, tid=140689104844544

 JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.73-b02 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libnd4jcpu.so+0x9db90]  _ZN7simdOps6Im2colIfE11execSpecialEPfPiS2_S3_S2_S3_S3_._omp_fn.987+0x3f0

 Core dump written. Default location: /opt/filter-server/filter-server-0.1.0/core or core.11330

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x00007ff4ac01e000):  JavaThread "worker-thread-13" [_thread_in_native, id=17165, stack(0x00007ff4bc0e3000,0x00007ff4bc1e4000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x00007ff32bffd000

Registers:
RAX=0x0000000000000095, RBX=0x0000000000000004, RCX=0x0000000000000700, RDX=0x00007ff380aa6bd0
RSP=0x00007ff4bc1e1e10, RBP=0x00000000000004b0, RSI=0x00007ff32bffc900, RDI=0x0000000000000020
R8 =0x0000000000000000, R9 =0x000000000000012c, R10=0x000000000000012c, R11=0x00000000000004b0
R12=0x000000000000012c, R13=0x00007ff4bc1e1fc0, R14=0x0000000000000001, R15=0x0000000000000004
RIP=0x00007ff55834cb90, EFLAGS=0x0000000000010207, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007ff4bc1e1e10)
0x00007ff4bc1e1e10:   0000005e00000048 00000000bc1e1e70
0x00007ff4bc1e1e20:   00000000000004b0 0000000000000000
0x00007ff4bc1e1e30:   00000000000004b0 00007ff32bfcd69c
0x00007ff4bc1e1e40:   00000000000020d0 0000000000000020
...
Stack: [0x00007ff4bc0e3000,0x00007ff4bc1e4000],  sp=0x00007ff4bc1e1e10,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnd4jcpu.so+0x9db90]  _ZN7simdOps6Im2colIfE11execSpecialEPfPiS2_S3_S2_S3_S3_._omp_fn.987+0x3f0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 4429  org.nd4j.nativeblas.Nd4jCpu$NativeOps.execTransformFloat(Lorg/bytedeco/javacpp/PointerPointer;ILorg/bytedeco/javacpp/FloatPointer;Lorg/bytedeco/javacpp/IntPointer;Lorg/bytedeco/javacpp/FloatPointer;
Lorg/bytedeco/javacpp/IntPointer;Lorg/bytedeco/javacpp/FloatPointer;)V (0 bytes) @ 0x00007ff5d5b1ab3b [0x00007ff5d5b1aa80+0xbb]
J 4774 C2 org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/TransformOp;)V (1472 bytes) @ 0x00007ff5d5ea54cc [0x00007ff5d5ea4b60+0x96c]
J 5530 C2 org.nd4j.linalg.convolution.Convolution.im2col(Lorg/nd4j/linalg/api/ndarray/INDArray;IIIIIIZLorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray; (39 bytes) @ 0x00007ff5d5f
c22a4 [0x00007ff5d5fc1b00+0x7a4]
J 5635 C2 org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(Z)Lorg/nd4j/linalg/api/ndarray/INDArray; (847 bytes) @ 0x00007ff5d60eec44 [0x00007ff5d60ed680+0x15c4]
J 5529 C2 org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(Z)Lorg/nd4j/linalg/api/ndarray/INDArray; (98 bytes) @ 0x00007ff5d5ce0044 [0x00007ff5d5cdffe0+0x64]
J 5403 C2 org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ZZ)Ljava/util/Map; (314 bytes) @ 0x00007ff5d604befc [0x00007ff5d604b6c0+0x83c]`
I'm not familiar with c/c++, is this a libnd4j bug? or my fault usage?

**Comment by saudet** [comment]
Probably a bug in ND4J somewhere. Could you provide a code snippet to reproduce this? Along with details about the versions, your system, etc.

**Comment by anzhilin** [comment]
@saudet actually i'm not use ND4j directly.i use this lib:
[https://github.com/deeplearning4j/deeplearning4j](url)
so i'm not sure is this code snippet correctly
`
import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.util.ModelSerializer;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.INDArrayIndex;
import org.nd4j.linalg.indexing.NDArrayIndex;

public class SentenceAnalysis {

private ComputationGraph computationGraph;
private WordVectors wordVectors;
public double analysis(String words) throws Exception { 
        double result=0.0;
        INDArray features = loadFeaturesFromString(words, wordVectors);
        INDArray networkOutput;
        if(features!=null){
            networkOutput = computationGraph.outputSingle(features);
            result = networkOutput.getDouble(1);
        }
        return result;
    }
`
libnd4j version:0.8.0
deeplearning4j version:0.8.0
os version:CentOS7.4
jdk version:1.8.0_73

**Comment by saudet** [comment]
> deeplearning4j version:0.8.0

Please try again with 0.9.1 and let us know if it still happens.

**Comment by anzhilin** [comment]
ok i'll try it.thank you. @saudet

**Comment by anzhilin** [comment]
@saudet still the same error after running some hours later

**Comment by anzhilin** [comment]
@saudet this is the gdb bt command output:
(gdb) bt
#0  0x00007f6fea12a1f7 in raise () from /lib64/libc.so.6
#1  0x00007f6fea12b8e8 in abort () from /lib64/libc.so.6
#2  0x00007f6fe9a31445 in os::abort(bool) () from /opt/jdk1.8.0_73/jre/lib/amd64/server/libjvm.so
#3  0x00007f6fe9bcfb23 in VMError::report_and_die() () from /opt/jdk1.8.0_73/jre/lib/amd64/server/libjvm.so
#4  0x00007f6fe9a36c6f in JVM_handle_linux_signal () from /opt/jdk1.8.0_73/jre/lib/amd64/server/libjvm.so
#5  0x00007f6fe9a2d403 in signalHandler(int, siginfo*, void*) () from /opt/jdk1.8.0_73/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00007f6f80775a20 in simdOps::Im2col<float>::execSpecial(float*, int*, float*, int*, float*, int*, long long*) [clone ._omp_fn.1180] ()
   from /root/.javacpp/cache/filter-server-0.1.0-jar-with-dependencies.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
#8  0x00007f6f81096aed in GOMP_parallel () from /root/.javacpp/cache/filter-server-0.1.0-jar-with-dependencies.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
#9  0x00007f6f80913ffb in NativeOps::execTransformFloat(void**, int, float*, int*, float*, int*, float*) ()
   from /root/.javacpp/cache/filter-server-0.1.0-jar-with-dependencies.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
#10 0x00007f6f558897e8 in Java_org_nd4j_nativeblas_Nd4jCpu_00024NativeOps_execTransformFloat__Lorg_bytedeco_javacpp_PointerPointer_2ILorg_bytedeco_javacpp_FloatPointer_2Lorg_bytedeco_javacpp_IntPointer_2Lorg_bytedeco_javacpp_FloatPointer_2Lorg_bytedeco_javacpp_IntPointer_2Lorg_bytedeco_javacpp_FloatPointer_2 ()
   from /root/.javacpp/cache/filter-server-0.1.0-jar-with-dependencies.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so

**Comment by raver119** [comment]
1) Show your neural network configuration please. First guess here: something bad breaks through validation.
2) Try with snapshots (0.9.2-SNAPSHOT) as well. There were some fixes applied recently.

**Comment by anzhilin** [comment]
running one day with no crash after i increase the jvm heap size

**Comment by raver119** [comment]
Native code isn't affected by jvm heap settings... It should be something else "fixed" problem.
