### ISSUE TITLE
DepthToSpace output shape is wrong?

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#719]
4,4,16,16

block size 4

isNWHC: 1

outputs: 4,0,64,64

**Comment by raver119** [comment]
Can't confirm this issue, sorry.
Here's test: https://github.com/deeplearning4j/libnd4j/blob/e8cfb66c61990ef4b0bf0ca60867b83efe6ec869/tests_cpu/layers_tests/DeclarableOpsTests4.cpp#L689

It passes.
old depth: 16; new depth: 16 / (block * block) = 1
old H: 4; new H: 4 * 4 = 16;
old W: 16: new W: 16 * 4 = 64;

So, expected output shape: [4, 16, 64, 1]

**Comment by raver119** [comment]
Aha. Issue is simple: wrong args order: block_size goes first, dataFormat goes second. Mapping issue.

**Comment by raver119** [comment]
p.s. i've applied fixes in your branch.
