### ISSUE TITLE
maxpool2d_bp fails on "weird" INDArray inputs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#755]
Main issue and (Java) tests to reproduce:
https://github.com/deeplearning4j/nd4j/issues/2517

**Comment by AlexDBlack** [comment]
Also relevant: maxpool2d_bp has different handling of padding vs. the forward pass (maxpool2d) op:
https://github.com/deeplearning4j/deeplearning4j/issues/4583#issuecomment-362160627

**Comment by raver119** [comment]
Confirmed as fixed by @AlexDBlack
