### ISSUE TITLE
IsMax-Operation: Faulty line reseting input, not result?

### ISSUE THREAD

**Issue by Ucomania** [deeplearning4j/libnd4j#786]
While inspecting the code, I noticed that in the following line (
https://github.com/deeplearning4j/libnd4j/blob/33214f3af7bb4c751db90704ff7c27ce90df1f5f/include/ops/special_ops.h#L2071
), the input to the operation is set to 0. I would expect this line to be 
"result[i] = (T)0;", not "dx[i] = 0.0;"
-> this would match the operation for elementWiseStride > 1 (line 2116), as well as those for OpenMP-parallel processing (2087 and 2132).
I am currently unable to verify that this code has implications, but most of the time, result arrays will be set to 0 before calling the function anyways.

**Comment by raver119** [comment]
Yes, that's a bug. Thanks for highlighting. Fixed in my branch, will merge later.
