### ISSUE TITLE
IsMax::execSpecialCuda only specified for computing whole-array-maximum?

### ISSUE THREAD

**Issue by Ucomania** [deeplearning4j/libnd4j#798]
I am only inferring the following from looking at code (Can't run CUDA-code at the moment):

Aren't the following lines missing an 'else'-branch? The if-clause is only matched when the maximum is computed over the whole array.
https://github.com/deeplearning4j/libnd4j/blob/d2d17716af0976f051cfaaab5cee5996f81e42f5/include/ops/special_ops.h#L2033-L2036
I couldn't find any reason in the trace between the executioner code [here](https://github.com/deeplearning4j/nd4j/blob/82262ba2f50dcbeacf33cfa8fbbc526e5f8eb748/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/ops/executioner/CudaExecutioner.java#L1403-L1665) and the execSpecialCuda-function that would make sure 'extraParams' would be set to nullptr or MAX_DIMENSION/Integer.MAX_VALUE. 
My assumption is therefore, that IsMax isn't doing anything when running on CUDA and dimensions specified. Unfortunately, I couldn't find a test that would convince me otherwise.

**Comment by raver119** [comment]
Yep, you're absolutely right here. This code isn't used at all. IsMax is special snowflake, and handled in few separate op calls, atm managed by NativeOps, in next release this op already CustomOp though, and legacy op will be removed for both cpu and cuda.
