### ISSUE TITLE
Errors when I run buildnativeoperations.sh on Ubuntu 

### ISSUE THREAD

**Issue by bazinga29** [deeplearning4j/libnd4j#830]
OS: Ubuntu 16.04.3 LTS
Cmake version: 3.10.2

Running buildnativeoperations.sh fails. Following are the errors seen:

buildnativeoperations.sh: 5: buildnativeoperations.sh: Bad substitution
eval cmake3
buildnativeoperations.sh: 15: buildnativeoperations.sh: [[: not found
buildnativeoperations.sh: 35: buildnativeoperations.sh: [[: not found
buildnativeoperations.sh: 97: [: Linux: unexpected operator
buildnativeoperations.sh: 101: [: Linux: unexpected operator
buildnativeoperations.sh: 101: [: Linu: unexpected operator
buildnativeoperations.sh: 105: [: x86_64: unexpected operator
buildnativeoperations.sh: 116: buildnativeoperations.sh: [[: not found
buildnativeoperations.sh: 300: [: unexpected operator
buildnativeoperations.sh: 300: [: unexpected operator
buildnativeoperations.sh: 303: [: unexpected operator
buildnativeoperations.sh: 303: [: unexpected operator
buildnativeoperations.sh: 306: [: unexpected operator
buildnativeoperations.sh: 306: [: unexpected operator
buildnativeoperations.sh: 319: [: cpu: unexpected operator
buildnativeoperations.sh: 325: [: dynamic: unexpected operator
buildnativeoperations.sh: 331: [: release: unexpected operator
buildnativeoperations.sh: 338: [: none: unexpected operator
buildnativeoperations.sh: 342: [: none: unexpected operator
buildnativeoperations.sh: 346: [: none: unexpected operator
buildnativeoperations.sh: 350: [: none: unexpected operator
buildnativeoperations.sh: 356: [: no: unexpected operator
buildnativeoperations.sh: 364: [: cpu: unexpected operator
PACKAGING = none
BUILD = release
CHIP = cpu
ARCH = x86-64
CHIP_EXTENSION = 
CHIP_VERSION = 
GPU_COMPUTE_CAPABILITY = all
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
buildnativeoperations.sh: 379: [: false: unexpected operator
/home/mlnow/sagar/libnd4j/blasbuild/cpu
buildnativeoperations.sh: 418: buildnativeoperations.sh: PACKAGING_ARG: parameter not set

**Comment by saudet** [comment]
It looks like your system is picking up something else than bash to run the script. Make sure it's using bash by executing `/path/to/bash buildnativeoperations.sh ...` instead.
