### ISSUE TITLE
Shape info spam during ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/libnd4j#842]
Not sure *which* ops it's occuring on - but it's reproducable using any (and only?) the VPTree tests in DL4J:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/test/java/org/deeplearning4j/clustering/vptree/VpTreeNodeTest.java

It's not at the DL4J or ND4J level... I'm pretty sure one of the libnd4j ops is calling ```shape::printShapeInfoLinear``` somewhere...

![image](https://user-images.githubusercontent.com/2360237/37961176-5228a41c-3203-11e8-98eb-93fd6a802526.png)

**Comment by raver119** [comment]
Hypothetically fixed

**Comment by AlexDBlack** [comment]
Thanks - confirmed fixed - I'm not seeing this anymore :)
