### ISSUE TITLE
CentOS installation

### ISSUE THREAD

**Issue by Railer** [deeplearning4j/libnd4j#85]
While running ./buildnativeoperations.sh blas cpu I get the following errors (Centos), successfuly built on Ubuntu LTS.
https://gist.github.com/Railer/02e23571497bee1298d76c38b4566c97

**Comment by raver119** [comment]
I've just checked, cpu version compiles fine for me. Ubuntu here.

**Comment by treo** [comment]
@Railer said on gitter that it works fine on ubuntu too, but on centos 7 it doesn't want to compile, even with the same gcc version as on ubuntu (gcc 4.8.4).

**Comment by Railer** [comment]
@treo , yeah forgot to mention it, so I updated the comment to be more clarifying!

**Comment by raver119** [comment]
I've got the same problem, fixed it. Will merge later.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/libnd4j/pull/87
