### ISSUE TITLE
jvm crashed after concat operation

### ISSUE THREAD

**Issue by Sirius081** [deeplearning4j/libnd4j#865]
here is log 
[hs_err_pid31141.log](https://github.com/deeplearning4j/libnd4j/files/1934157/hs_err_pid31141.log)

I wonder what operations of concat contribute to the crash

**Comment by Sirius081** [comment]
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 16093  org.nd4j.nativeblas.Nd4jCpu$NativeOps.concatFloat(Lorg/bytedeco/javacpp/PointerPointer;IILorg/bytedeco/javacpp/PointerPointer;Lorg/bytedeco/javacpp/PointerPointer;Lorg/bytedeco/javacpp/FloatPointer;Lorg/bytedeco/javacpp/IntPointer;Lorg/bytedeco/javacpp/PointerPointer;Lorg/bytedeco/javacpp/PointerPointer;)V (0 bytes) @ 0x00002b479a0c4d93 [0x00002b479a0c4cc0+0xd3]
J 19627 C2 org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.concat(I[Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray; (672 bytes) @ 0x00002b479c348d58 [0x00002b479c3482a0+0xab8]
J 16954 C2 com.dp.arts.rerank.model.task.ModelPredictTask.run()V (576 bytes) @ 0x00002b479b53599c [0x00002b479b534e00+0xb9c]
J 20374 C2 com.dp.arts.rerank.model.task.ModelPredictTask.call()Ljava/lang/Object; (5 bytes) @ 0x00002b479814d734 [0x00002b479814d700+0x34]
J 26386 C2 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x00002b479af38050 [0x00002b479af37fa0+0xb0]
J 10722 C1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00002b4799769384 [0x00002b4799768360+0x1024]
J 13507 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00002b4799d6cf04 [0x00002b4799d6ce00+0x104]
J 12307 C1 java.lang.Thread.run()V (17 bytes) @ 0x00002b479a241bc4 [0x00002b479a241a80+0x144]
v  ~StubRoutines::call_stub


here is log

**Comment by treo** [comment]
Can you post the code that resulted in this crash? Or even better, can you create a minimal example that results in the problem?

**Comment by raver119** [comment]
Yes please. Crash log on it's own doesn't tell us too much

**Comment by Sirius081** [comment]
The code is too complex to show. It's a part of our online environment
what may be the reasons for this crash? the log shows 'concat' resulted in the crash..

**Comment by agibsonccc** [comment]
@Sirius081 if you can't give us any information, I have to treat this as irrelevant. Only re open this if you can actually help us reproduce it.

**Comment by treo** [comment]
@Sirius081 Given just your crash log I can only tell you that you are probably running something in a threaded environment that isn't thread safe:

> J 16954 C2 com.dp.arts.rerank.model.task.ModelPredictTask.run()V (576 bytes) @ 0x00002b479b53599c [0x00002b479b534e00+0xb9c]
J 20374 C2 com.dp.arts.rerank.model.task.ModelPredictTask.call()Ljava/lang/Object; (5 bytes) @ 0x00002b479814d734 [0x00002b479814d700+0x34]
J 26386 C2 **java.util.concurrent.FutureTask.run**()V (126 bytes) @ 0x00002b479af38050 [0x00002b479af37fa0+0xb0]
J 10722 C1 **java.util.concurrent.ThreadPoolExecutor.runWorker**(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00002b4799769384 [0x00002b4799768360+0x1024]

So without any more information on what exactly you are doing, you are on your own there.

**Comment by Sirius081** [comment]
`public INDArray getBatchFeatures(RerankContext rerankContext, int segmentID, List<Integer> instanceIds, ArrayList<String> feaList, boolean useEmbedding) {
        INDArray features = getFeatures(rerankContext, segmentID, instanceIds, feaList);
        if (useEmbedding) {
            INDArray embeddings = getEmbeddings(rerankContext, segmentID, instanceIds);
            features = Nd4j.concat(1, embeddings, features);
        }
       `
`
private INDArray getFeatures(RerankContext rerankContext, int segmentID, List<Integer> instanceIds, ArrayList<String> feaList) {
        int batchSize = instanceIds.size();
        double[][] featureMatrix = new double[batchSize][feaList.size()];
       //delete code which assigns value to featureMatrix. The code is about our business
        INDArray features = Nd4j.create(featureMatrix);
        features.subiRowVector(gapmin).diviRowVector(gap);
        return features;
    }
`
`
public INDArray getEmbeddings(RerankContext rerankContext, int segmentId, List<Integer> instanceIds) {
        int batchSize = instanceIds.size();
        FeatureData featureData = rerankContext.getFeatureDataFromMap(segmentId);
        INDArray embeddings = Nd4j.zeros(batchSize, embTotalDim);
       //delete code which assigns value to featureMatrix. The code is about our business
        return embeddings;
    }
`


one thing may help is that the physical memory is almost exhausted

**Comment by emillynge** [comment]
I've also had problems with concat in a threaded environment see #536 
I ended up implementing my own dumb version of concat in java as I could not reliable reproduce the issue and running valgrind was too slow to ever trigger the fault.

I get that nd4j is not thread safe. but problem is that I have no idea which ops in nd4j that are not thread safe. I have very long running Java applications running in a threaded environment using Nd4j, so to some extent it must be thread safe. Or at least, parts of nd4j must be thread safe.

Right now I'm experiencing similar issues with `pullRows` and I almost can't be bothered to figure out how to call that method safely.

**Comment by saudet** [comment]
@emillynge If you could come up with a code snippet (that creates 1000 threads if you need) to reproduce your issue, it would also help a lot.

**Comment by emillynge** [comment]
@saudet If I can reproduce the problem with pullRows I will file a separate issue.
But the issue _is_ very rare ~ occurs once in 5-10 hours of running my application.

But as said, I simply revert to implementing similar functionality in pure java (which is calling `Pointer.memcpy` directly :confused: ) As my experience tells me I will end up spending lots of time reproducing the bug to no avail.
